// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: ClientMessage.proto

package com.randioo.market_server.protocol;

public final class ClientMessage {
  private ClientMessage() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class CS extends
      com.google.protobuf.GeneratedMessage {
    // Use CS.newBuilder() to construct.
    private CS() {
      initFields();
    }
    private CS(boolean noInit) {}
    
    private static final CS defaultInstance;
    public static CS getDefaultInstance() {
      return defaultInstance;
    }
    
    public CS getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.market_server.protocol.ClientMessage.internal_static_com_randioo_market_server_protocol_CS_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.market_server.protocol.ClientMessage.internal_static_com_randioo_market_server_protocol_CS_fieldAccessorTable;
    }
    
    // optional .com.randioo.market_server.protocol.HeartRequest HeartRequest = 1;
    public static final int HEARTREQUEST_FIELD_NUMBER = 1;
    private boolean hasHeartRequest;
    private com.randioo.market_server.protocol.Heart.HeartRequest heartRequest_;
    public boolean hasHeartRequest() { return hasHeartRequest; }
    public com.randioo.market_server.protocol.Heart.HeartRequest getHeartRequest() { return heartRequest_; }
    
    // optional .com.randioo.market_server.protocol.LoginCheckAccountRequest LoginCheckAccountRequest = 2;
    public static final int LOGINCHECKACCOUNTREQUEST_FIELD_NUMBER = 2;
    private boolean hasLoginCheckAccountRequest;
    private com.randioo.market_server.protocol.Login.LoginCheckAccountRequest loginCheckAccountRequest_;
    public boolean hasLoginCheckAccountRequest() { return hasLoginCheckAccountRequest; }
    public com.randioo.market_server.protocol.Login.LoginCheckAccountRequest getLoginCheckAccountRequest() { return loginCheckAccountRequest_; }
    
    // optional .com.randioo.market_server.protocol.GmCmdRequest GmCmdRequest = 3;
    public static final int GMCMDREQUEST_FIELD_NUMBER = 3;
    private boolean hasGmCmdRequest;
    private com.randioo.market_server.protocol.Gm.GmCmdRequest gmCmdRequest_;
    public boolean hasGmCmdRequest() { return hasGmCmdRequest; }
    public com.randioo.market_server.protocol.Gm.GmCmdRequest getGmCmdRequest() { return gmCmdRequest_; }
    
    // optional .com.randioo.market_server.protocol.LoginCreateRoleRequest LoginCreateRoleRequest = 4;
    public static final int LOGINCREATEROLEREQUEST_FIELD_NUMBER = 4;
    private boolean hasLoginCreateRoleRequest;
    private com.randioo.market_server.protocol.Login.LoginCreateRoleRequest loginCreateRoleRequest_;
    public boolean hasLoginCreateRoleRequest() { return hasLoginCreateRoleRequest; }
    public com.randioo.market_server.protocol.Login.LoginCreateRoleRequest getLoginCreateRoleRequest() { return loginCreateRoleRequest_; }
    
    // optional .com.randioo.market_server.protocol.LoginGetRoleDataRequest LoginGetRoleDataRequest = 5;
    public static final int LOGINGETROLEDATAREQUEST_FIELD_NUMBER = 5;
    private boolean hasLoginGetRoleDataRequest;
    private com.randioo.market_server.protocol.Login.LoginGetRoleDataRequest loginGetRoleDataRequest_;
    public boolean hasLoginGetRoleDataRequest() { return hasLoginGetRoleDataRequest; }
    public com.randioo.market_server.protocol.Login.LoginGetRoleDataRequest getLoginGetRoleDataRequest() { return loginGetRoleDataRequest_; }
    
    // optional .com.randioo.market_server.protocol.SystemInfoRequest SystemInfoRequest = 6;
    public static final int SYSTEMINFOREQUEST_FIELD_NUMBER = 6;
    private boolean hasSystemInfoRequest;
    private com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest systemInfoRequest_;
    public boolean hasSystemInfoRequest() { return hasSystemInfoRequest; }
    public com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest getSystemInfoRequest() { return systemInfoRequest_; }
    
    // optional .com.randioo.market_server.protocol.GoodsTyRequest GoodsTyRequest = 7;
    public static final int GOODSTYREQUEST_FIELD_NUMBER = 7;
    private boolean hasGoodsTyRequest;
    private com.randioo.market_server.protocol.GoodsTy.GoodsTyRequest goodsTyRequest_;
    public boolean hasGoodsTyRequest() { return hasGoodsTyRequest; }
    public com.randioo.market_server.protocol.GoodsTy.GoodsTyRequest getGoodsTyRequest() { return goodsTyRequest_; }
    
    // optional .com.randioo.market_server.protocol.UserInfoRequest UserInfoRequest = 8;
    public static final int USERINFOREQUEST_FIELD_NUMBER = 8;
    private boolean hasUserInfoRequest;
    private com.randioo.market_server.protocol.UserInfo.UserInfoRequest userInfoRequest_;
    public boolean hasUserInfoRequest() { return hasUserInfoRequest; }
    public com.randioo.market_server.protocol.UserInfo.UserInfoRequest getUserInfoRequest() { return userInfoRequest_; }
    
    // optional .com.randioo.market_server.protocol.SellerMyRequest SellerMyRequest = 9;
    public static final int SELLERMYREQUEST_FIELD_NUMBER = 9;
    private boolean hasSellerMyRequest;
    private com.randioo.market_server.protocol.Seller.SellerMyRequest sellerMyRequest_;
    public boolean hasSellerMyRequest() { return hasSellerMyRequest; }
    public com.randioo.market_server.protocol.Seller.SellerMyRequest getSellerMyRequest() { return sellerMyRequest_; }
    
    // optional .com.randioo.market_server.protocol.SellerRequest SellerRequest = 10;
    public static final int SELLERREQUEST_FIELD_NUMBER = 10;
    private boolean hasSellerRequest;
    private com.randioo.market_server.protocol.Seller.SellerRequest sellerRequest_;
    public boolean hasSellerRequest() { return hasSellerRequest; }
    public com.randioo.market_server.protocol.Seller.SellerRequest getSellerRequest() { return sellerRequest_; }
    
    // optional .com.randioo.market_server.protocol.BuyerRequest BuyerRequest = 11;
    public static final int BUYERREQUEST_FIELD_NUMBER = 11;
    private boolean hasBuyerRequest;
    private com.randioo.market_server.protocol.Buyer.BuyerRequest buyerRequest_;
    public boolean hasBuyerRequest() { return hasBuyerRequest; }
    public com.randioo.market_server.protocol.Buyer.BuyerRequest getBuyerRequest() { return buyerRequest_; }
    
    // optional .com.randioo.market_server.protocol.RevokeSellerRequest RevokeSellerRequest = 12;
    public static final int REVOKESELLERREQUEST_FIELD_NUMBER = 12;
    private boolean hasRevokeSellerRequest;
    private com.randioo.market_server.protocol.Seller.RevokeSellerRequest revokeSellerRequest_;
    public boolean hasRevokeSellerRequest() { return hasRevokeSellerRequest; }
    public com.randioo.market_server.protocol.Seller.RevokeSellerRequest getRevokeSellerRequest() { return revokeSellerRequest_; }
    
    // optional .com.randioo.market_server.protocol.GoodsRequest GoodsRequest = 13;
    public static final int GOODSREQUEST_FIELD_NUMBER = 13;
    private boolean hasGoodsRequest;
    private com.randioo.market_server.protocol.Goods.GoodsRequest goodsRequest_;
    public boolean hasGoodsRequest() { return hasGoodsRequest; }
    public com.randioo.market_server.protocol.Goods.GoodsRequest getGoodsRequest() { return goodsRequest_; }
    
    // optional .com.randioo.market_server.protocol.DealRequest DealRequest = 14;
    public static final int DEALREQUEST_FIELD_NUMBER = 14;
    private boolean hasDealRequest;
    private com.randioo.market_server.protocol.Deal.DealRequest dealRequest_;
    public boolean hasDealRequest() { return hasDealRequest; }
    public com.randioo.market_server.protocol.Deal.DealRequest getDealRequest() { return dealRequest_; }
    
    // optional .com.randioo.market_server.protocol.KRequest KRequest = 15;
    public static final int KREQUEST_FIELD_NUMBER = 15;
    private boolean hasKRequest;
    private com.randioo.market_server.protocol.K.KRequest kRequest_;
    public boolean hasKRequest() { return hasKRequest; }
    public com.randioo.market_server.protocol.K.KRequest getKRequest() { return kRequest_; }
    
    // optional .com.randioo.market_server.protocol.DayClickRequest DayClickRequest = 16;
    public static final int DAYCLICKREQUEST_FIELD_NUMBER = 16;
    private boolean hasDayClickRequest;
    private com.randioo.market_server.protocol.K.DayClickRequest dayClickRequest_;
    public boolean hasDayClickRequest() { return hasDayClickRequest; }
    public com.randioo.market_server.protocol.K.DayClickRequest getDayClickRequest() { return dayClickRequest_; }
    
    // optional .com.randioo.market_server.protocol.MinkClickRequest MinkClickRequest = 17;
    public static final int MINKCLICKREQUEST_FIELD_NUMBER = 17;
    private boolean hasMinkClickRequest;
    private com.randioo.market_server.protocol.K.MinkClickRequest minkClickRequest_;
    public boolean hasMinkClickRequest() { return hasMinkClickRequest; }
    public com.randioo.market_server.protocol.K.MinkClickRequest getMinkClickRequest() { return minkClickRequest_; }
    
    // optional .com.randioo.market_server.protocol.OneMinkRequest OneMinkRequest = 18;
    public static final int ONEMINKREQUEST_FIELD_NUMBER = 18;
    private boolean hasOneMinkRequest;
    private com.randioo.market_server.protocol.K.OneMinkRequest oneMinkRequest_;
    public boolean hasOneMinkRequest() { return hasOneMinkRequest; }
    public com.randioo.market_server.protocol.K.OneMinkRequest getOneMinkRequest() { return oneMinkRequest_; }
    
    // optional .com.randioo.market_server.protocol.FifMinkRequest FifMinkRequest = 19;
    public static final int FIFMINKREQUEST_FIELD_NUMBER = 19;
    private boolean hasFifMinkRequest;
    private com.randioo.market_server.protocol.K.FifMinkRequest fifMinkRequest_;
    public boolean hasFifMinkRequest() { return hasFifMinkRequest; }
    public com.randioo.market_server.protocol.K.FifMinkRequest getFifMinkRequest() { return fifMinkRequest_; }
    
    // optional .com.randioo.market_server.protocol.ThirtyMinkRequest ThirtyMinkRequest = 20;
    public static final int THIRTYMINKREQUEST_FIELD_NUMBER = 20;
    private boolean hasThirtyMinkRequest;
    private com.randioo.market_server.protocol.K.ThirtyMinkRequest thirtyMinkRequest_;
    public boolean hasThirtyMinkRequest() { return hasThirtyMinkRequest; }
    public com.randioo.market_server.protocol.K.ThirtyMinkRequest getThirtyMinkRequest() { return thirtyMinkRequest_; }
    
    // optional .com.randioo.market_server.protocol.SixMinkRequest SixMinkRequest = 21;
    public static final int SIXMINKREQUEST_FIELD_NUMBER = 21;
    private boolean hasSixMinkRequest;
    private com.randioo.market_server.protocol.K.SixMinkRequest sixMinkRequest_;
    public boolean hasSixMinkRequest() { return hasSixMinkRequest; }
    public com.randioo.market_server.protocol.K.SixMinkRequest getSixMinkRequest() { return sixMinkRequest_; }
    
    // optional .com.randioo.market_server.protocol.CSHeart CSHeart = 22;
    public static final int CSHEART_FIELD_NUMBER = 22;
    private boolean hasCSHeart;
    private com.randioo.market_server.protocol.Heart.CSHeart cSHeart_;
    public boolean hasCSHeart() { return hasCSHeart; }
    public com.randioo.market_server.protocol.Heart.CSHeart getCSHeart() { return cSHeart_; }
    
    // optional .com.randioo.market_server.protocol.ActiveInfoRequest ActiveInfoRequest = 23;
    public static final int ACTIVEINFOREQUEST_FIELD_NUMBER = 23;
    private boolean hasActiveInfoRequest;
    private com.randioo.market_server.protocol.UserInfo.ActiveInfoRequest activeInfoRequest_;
    public boolean hasActiveInfoRequest() { return hasActiveInfoRequest; }
    public com.randioo.market_server.protocol.UserInfo.ActiveInfoRequest getActiveInfoRequest() { return activeInfoRequest_; }
    
    private void initFields() {
      heartRequest_ = com.randioo.market_server.protocol.Heart.HeartRequest.getDefaultInstance();
      loginCheckAccountRequest_ = com.randioo.market_server.protocol.Login.LoginCheckAccountRequest.getDefaultInstance();
      gmCmdRequest_ = com.randioo.market_server.protocol.Gm.GmCmdRequest.getDefaultInstance();
      loginCreateRoleRequest_ = com.randioo.market_server.protocol.Login.LoginCreateRoleRequest.getDefaultInstance();
      loginGetRoleDataRequest_ = com.randioo.market_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance();
      systemInfoRequest_ = com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest.getDefaultInstance();
      goodsTyRequest_ = com.randioo.market_server.protocol.GoodsTy.GoodsTyRequest.getDefaultInstance();
      userInfoRequest_ = com.randioo.market_server.protocol.UserInfo.UserInfoRequest.getDefaultInstance();
      sellerMyRequest_ = com.randioo.market_server.protocol.Seller.SellerMyRequest.getDefaultInstance();
      sellerRequest_ = com.randioo.market_server.protocol.Seller.SellerRequest.getDefaultInstance();
      buyerRequest_ = com.randioo.market_server.protocol.Buyer.BuyerRequest.getDefaultInstance();
      revokeSellerRequest_ = com.randioo.market_server.protocol.Seller.RevokeSellerRequest.getDefaultInstance();
      goodsRequest_ = com.randioo.market_server.protocol.Goods.GoodsRequest.getDefaultInstance();
      dealRequest_ = com.randioo.market_server.protocol.Deal.DealRequest.getDefaultInstance();
      kRequest_ = com.randioo.market_server.protocol.K.KRequest.getDefaultInstance();
      dayClickRequest_ = com.randioo.market_server.protocol.K.DayClickRequest.getDefaultInstance();
      minkClickRequest_ = com.randioo.market_server.protocol.K.MinkClickRequest.getDefaultInstance();
      oneMinkRequest_ = com.randioo.market_server.protocol.K.OneMinkRequest.getDefaultInstance();
      fifMinkRequest_ = com.randioo.market_server.protocol.K.FifMinkRequest.getDefaultInstance();
      thirtyMinkRequest_ = com.randioo.market_server.protocol.K.ThirtyMinkRequest.getDefaultInstance();
      sixMinkRequest_ = com.randioo.market_server.protocol.K.SixMinkRequest.getDefaultInstance();
      cSHeart_ = com.randioo.market_server.protocol.Heart.CSHeart.getDefaultInstance();
      activeInfoRequest_ = com.randioo.market_server.protocol.UserInfo.ActiveInfoRequest.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasHeartRequest()) {
        output.writeMessage(1, getHeartRequest());
      }
      if (hasLoginCheckAccountRequest()) {
        output.writeMessage(2, getLoginCheckAccountRequest());
      }
      if (hasGmCmdRequest()) {
        output.writeMessage(3, getGmCmdRequest());
      }
      if (hasLoginCreateRoleRequest()) {
        output.writeMessage(4, getLoginCreateRoleRequest());
      }
      if (hasLoginGetRoleDataRequest()) {
        output.writeMessage(5, getLoginGetRoleDataRequest());
      }
      if (hasSystemInfoRequest()) {
        output.writeMessage(6, getSystemInfoRequest());
      }
      if (hasGoodsTyRequest()) {
        output.writeMessage(7, getGoodsTyRequest());
      }
      if (hasUserInfoRequest()) {
        output.writeMessage(8, getUserInfoRequest());
      }
      if (hasSellerMyRequest()) {
        output.writeMessage(9, getSellerMyRequest());
      }
      if (hasSellerRequest()) {
        output.writeMessage(10, getSellerRequest());
      }
      if (hasBuyerRequest()) {
        output.writeMessage(11, getBuyerRequest());
      }
      if (hasRevokeSellerRequest()) {
        output.writeMessage(12, getRevokeSellerRequest());
      }
      if (hasGoodsRequest()) {
        output.writeMessage(13, getGoodsRequest());
      }
      if (hasDealRequest()) {
        output.writeMessage(14, getDealRequest());
      }
      if (hasKRequest()) {
        output.writeMessage(15, getKRequest());
      }
      if (hasDayClickRequest()) {
        output.writeMessage(16, getDayClickRequest());
      }
      if (hasMinkClickRequest()) {
        output.writeMessage(17, getMinkClickRequest());
      }
      if (hasOneMinkRequest()) {
        output.writeMessage(18, getOneMinkRequest());
      }
      if (hasFifMinkRequest()) {
        output.writeMessage(19, getFifMinkRequest());
      }
      if (hasThirtyMinkRequest()) {
        output.writeMessage(20, getThirtyMinkRequest());
      }
      if (hasSixMinkRequest()) {
        output.writeMessage(21, getSixMinkRequest());
      }
      if (hasCSHeart()) {
        output.writeMessage(22, getCSHeart());
      }
      if (hasActiveInfoRequest()) {
        output.writeMessage(23, getActiveInfoRequest());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasHeartRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getHeartRequest());
      }
      if (hasLoginCheckAccountRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getLoginCheckAccountRequest());
      }
      if (hasGmCmdRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(3, getGmCmdRequest());
      }
      if (hasLoginCreateRoleRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(4, getLoginCreateRoleRequest());
      }
      if (hasLoginGetRoleDataRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(5, getLoginGetRoleDataRequest());
      }
      if (hasSystemInfoRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(6, getSystemInfoRequest());
      }
      if (hasGoodsTyRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(7, getGoodsTyRequest());
      }
      if (hasUserInfoRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(8, getUserInfoRequest());
      }
      if (hasSellerMyRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(9, getSellerMyRequest());
      }
      if (hasSellerRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(10, getSellerRequest());
      }
      if (hasBuyerRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(11, getBuyerRequest());
      }
      if (hasRevokeSellerRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(12, getRevokeSellerRequest());
      }
      if (hasGoodsRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(13, getGoodsRequest());
      }
      if (hasDealRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(14, getDealRequest());
      }
      if (hasKRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(15, getKRequest());
      }
      if (hasDayClickRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(16, getDayClickRequest());
      }
      if (hasMinkClickRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(17, getMinkClickRequest());
      }
      if (hasOneMinkRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(18, getOneMinkRequest());
      }
      if (hasFifMinkRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(19, getFifMinkRequest());
      }
      if (hasThirtyMinkRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(20, getThirtyMinkRequest());
      }
      if (hasSixMinkRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(21, getSixMinkRequest());
      }
      if (hasCSHeart()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(22, getCSHeart());
      }
      if (hasActiveInfoRequest()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(23, getActiveInfoRequest());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.market_server.protocol.ClientMessage.CS parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.ClientMessage.CS parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.ClientMessage.CS parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.ClientMessage.CS parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.ClientMessage.CS parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.ClientMessage.CS parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.ClientMessage.CS parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.ClientMessage.CS parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.ClientMessage.CS parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.ClientMessage.CS parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.market_server.protocol.ClientMessage.CS prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.market_server.protocol.ClientMessage.CS result;
      
      // Construct using com.randioo.market_server.protocol.ClientMessage.CS.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.market_server.protocol.ClientMessage.CS();
        return builder;
      }
      
      protected com.randioo.market_server.protocol.ClientMessage.CS internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.market_server.protocol.ClientMessage.CS();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.market_server.protocol.ClientMessage.CS.getDescriptor();
      }
      
      public com.randioo.market_server.protocol.ClientMessage.CS getDefaultInstanceForType() {
        return com.randioo.market_server.protocol.ClientMessage.CS.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.market_server.protocol.ClientMessage.CS build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.market_server.protocol.ClientMessage.CS buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.market_server.protocol.ClientMessage.CS buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.market_server.protocol.ClientMessage.CS returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.market_server.protocol.ClientMessage.CS) {
          return mergeFrom((com.randioo.market_server.protocol.ClientMessage.CS)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.market_server.protocol.ClientMessage.CS other) {
        if (other == com.randioo.market_server.protocol.ClientMessage.CS.getDefaultInstance()) return this;
        if (other.hasHeartRequest()) {
          mergeHeartRequest(other.getHeartRequest());
        }
        if (other.hasLoginCheckAccountRequest()) {
          mergeLoginCheckAccountRequest(other.getLoginCheckAccountRequest());
        }
        if (other.hasGmCmdRequest()) {
          mergeGmCmdRequest(other.getGmCmdRequest());
        }
        if (other.hasLoginCreateRoleRequest()) {
          mergeLoginCreateRoleRequest(other.getLoginCreateRoleRequest());
        }
        if (other.hasLoginGetRoleDataRequest()) {
          mergeLoginGetRoleDataRequest(other.getLoginGetRoleDataRequest());
        }
        if (other.hasSystemInfoRequest()) {
          mergeSystemInfoRequest(other.getSystemInfoRequest());
        }
        if (other.hasGoodsTyRequest()) {
          mergeGoodsTyRequest(other.getGoodsTyRequest());
        }
        if (other.hasUserInfoRequest()) {
          mergeUserInfoRequest(other.getUserInfoRequest());
        }
        if (other.hasSellerMyRequest()) {
          mergeSellerMyRequest(other.getSellerMyRequest());
        }
        if (other.hasSellerRequest()) {
          mergeSellerRequest(other.getSellerRequest());
        }
        if (other.hasBuyerRequest()) {
          mergeBuyerRequest(other.getBuyerRequest());
        }
        if (other.hasRevokeSellerRequest()) {
          mergeRevokeSellerRequest(other.getRevokeSellerRequest());
        }
        if (other.hasGoodsRequest()) {
          mergeGoodsRequest(other.getGoodsRequest());
        }
        if (other.hasDealRequest()) {
          mergeDealRequest(other.getDealRequest());
        }
        if (other.hasKRequest()) {
          mergeKRequest(other.getKRequest());
        }
        if (other.hasDayClickRequest()) {
          mergeDayClickRequest(other.getDayClickRequest());
        }
        if (other.hasMinkClickRequest()) {
          mergeMinkClickRequest(other.getMinkClickRequest());
        }
        if (other.hasOneMinkRequest()) {
          mergeOneMinkRequest(other.getOneMinkRequest());
        }
        if (other.hasFifMinkRequest()) {
          mergeFifMinkRequest(other.getFifMinkRequest());
        }
        if (other.hasThirtyMinkRequest()) {
          mergeThirtyMinkRequest(other.getThirtyMinkRequest());
        }
        if (other.hasSixMinkRequest()) {
          mergeSixMinkRequest(other.getSixMinkRequest());
        }
        if (other.hasCSHeart()) {
          mergeCSHeart(other.getCSHeart());
        }
        if (other.hasActiveInfoRequest()) {
          mergeActiveInfoRequest(other.getActiveInfoRequest());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.market_server.protocol.Heart.HeartRequest.Builder subBuilder = com.randioo.market_server.protocol.Heart.HeartRequest.newBuilder();
              if (hasHeartRequest()) {
                subBuilder.mergeFrom(getHeartRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setHeartRequest(subBuilder.buildPartial());
              break;
            }
            case 18: {
              com.randioo.market_server.protocol.Login.LoginCheckAccountRequest.Builder subBuilder = com.randioo.market_server.protocol.Login.LoginCheckAccountRequest.newBuilder();
              if (hasLoginCheckAccountRequest()) {
                subBuilder.mergeFrom(getLoginCheckAccountRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCheckAccountRequest(subBuilder.buildPartial());
              break;
            }
            case 26: {
              com.randioo.market_server.protocol.Gm.GmCmdRequest.Builder subBuilder = com.randioo.market_server.protocol.Gm.GmCmdRequest.newBuilder();
              if (hasGmCmdRequest()) {
                subBuilder.mergeFrom(getGmCmdRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGmCmdRequest(subBuilder.buildPartial());
              break;
            }
            case 34: {
              com.randioo.market_server.protocol.Login.LoginCreateRoleRequest.Builder subBuilder = com.randioo.market_server.protocol.Login.LoginCreateRoleRequest.newBuilder();
              if (hasLoginCreateRoleRequest()) {
                subBuilder.mergeFrom(getLoginCreateRoleRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginCreateRoleRequest(subBuilder.buildPartial());
              break;
            }
            case 42: {
              com.randioo.market_server.protocol.Login.LoginGetRoleDataRequest.Builder subBuilder = com.randioo.market_server.protocol.Login.LoginGetRoleDataRequest.newBuilder();
              if (hasLoginGetRoleDataRequest()) {
                subBuilder.mergeFrom(getLoginGetRoleDataRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setLoginGetRoleDataRequest(subBuilder.buildPartial());
              break;
            }
            case 50: {
              com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest.Builder subBuilder = com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest.newBuilder();
              if (hasSystemInfoRequest()) {
                subBuilder.mergeFrom(getSystemInfoRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSystemInfoRequest(subBuilder.buildPartial());
              break;
            }
            case 58: {
              com.randioo.market_server.protocol.GoodsTy.GoodsTyRequest.Builder subBuilder = com.randioo.market_server.protocol.GoodsTy.GoodsTyRequest.newBuilder();
              if (hasGoodsTyRequest()) {
                subBuilder.mergeFrom(getGoodsTyRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGoodsTyRequest(subBuilder.buildPartial());
              break;
            }
            case 66: {
              com.randioo.market_server.protocol.UserInfo.UserInfoRequest.Builder subBuilder = com.randioo.market_server.protocol.UserInfo.UserInfoRequest.newBuilder();
              if (hasUserInfoRequest()) {
                subBuilder.mergeFrom(getUserInfoRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setUserInfoRequest(subBuilder.buildPartial());
              break;
            }
            case 74: {
              com.randioo.market_server.protocol.Seller.SellerMyRequest.Builder subBuilder = com.randioo.market_server.protocol.Seller.SellerMyRequest.newBuilder();
              if (hasSellerMyRequest()) {
                subBuilder.mergeFrom(getSellerMyRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSellerMyRequest(subBuilder.buildPartial());
              break;
            }
            case 82: {
              com.randioo.market_server.protocol.Seller.SellerRequest.Builder subBuilder = com.randioo.market_server.protocol.Seller.SellerRequest.newBuilder();
              if (hasSellerRequest()) {
                subBuilder.mergeFrom(getSellerRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSellerRequest(subBuilder.buildPartial());
              break;
            }
            case 90: {
              com.randioo.market_server.protocol.Buyer.BuyerRequest.Builder subBuilder = com.randioo.market_server.protocol.Buyer.BuyerRequest.newBuilder();
              if (hasBuyerRequest()) {
                subBuilder.mergeFrom(getBuyerRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setBuyerRequest(subBuilder.buildPartial());
              break;
            }
            case 98: {
              com.randioo.market_server.protocol.Seller.RevokeSellerRequest.Builder subBuilder = com.randioo.market_server.protocol.Seller.RevokeSellerRequest.newBuilder();
              if (hasRevokeSellerRequest()) {
                subBuilder.mergeFrom(getRevokeSellerRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setRevokeSellerRequest(subBuilder.buildPartial());
              break;
            }
            case 106: {
              com.randioo.market_server.protocol.Goods.GoodsRequest.Builder subBuilder = com.randioo.market_server.protocol.Goods.GoodsRequest.newBuilder();
              if (hasGoodsRequest()) {
                subBuilder.mergeFrom(getGoodsRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setGoodsRequest(subBuilder.buildPartial());
              break;
            }
            case 114: {
              com.randioo.market_server.protocol.Deal.DealRequest.Builder subBuilder = com.randioo.market_server.protocol.Deal.DealRequest.newBuilder();
              if (hasDealRequest()) {
                subBuilder.mergeFrom(getDealRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setDealRequest(subBuilder.buildPartial());
              break;
            }
            case 122: {
              com.randioo.market_server.protocol.K.KRequest.Builder subBuilder = com.randioo.market_server.protocol.K.KRequest.newBuilder();
              if (hasKRequest()) {
                subBuilder.mergeFrom(getKRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setKRequest(subBuilder.buildPartial());
              break;
            }
            case 130: {
              com.randioo.market_server.protocol.K.DayClickRequest.Builder subBuilder = com.randioo.market_server.protocol.K.DayClickRequest.newBuilder();
              if (hasDayClickRequest()) {
                subBuilder.mergeFrom(getDayClickRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setDayClickRequest(subBuilder.buildPartial());
              break;
            }
            case 138: {
              com.randioo.market_server.protocol.K.MinkClickRequest.Builder subBuilder = com.randioo.market_server.protocol.K.MinkClickRequest.newBuilder();
              if (hasMinkClickRequest()) {
                subBuilder.mergeFrom(getMinkClickRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setMinkClickRequest(subBuilder.buildPartial());
              break;
            }
            case 146: {
              com.randioo.market_server.protocol.K.OneMinkRequest.Builder subBuilder = com.randioo.market_server.protocol.K.OneMinkRequest.newBuilder();
              if (hasOneMinkRequest()) {
                subBuilder.mergeFrom(getOneMinkRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setOneMinkRequest(subBuilder.buildPartial());
              break;
            }
            case 154: {
              com.randioo.market_server.protocol.K.FifMinkRequest.Builder subBuilder = com.randioo.market_server.protocol.K.FifMinkRequest.newBuilder();
              if (hasFifMinkRequest()) {
                subBuilder.mergeFrom(getFifMinkRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setFifMinkRequest(subBuilder.buildPartial());
              break;
            }
            case 162: {
              com.randioo.market_server.protocol.K.ThirtyMinkRequest.Builder subBuilder = com.randioo.market_server.protocol.K.ThirtyMinkRequest.newBuilder();
              if (hasThirtyMinkRequest()) {
                subBuilder.mergeFrom(getThirtyMinkRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setThirtyMinkRequest(subBuilder.buildPartial());
              break;
            }
            case 170: {
              com.randioo.market_server.protocol.K.SixMinkRequest.Builder subBuilder = com.randioo.market_server.protocol.K.SixMinkRequest.newBuilder();
              if (hasSixMinkRequest()) {
                subBuilder.mergeFrom(getSixMinkRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSixMinkRequest(subBuilder.buildPartial());
              break;
            }
            case 178: {
              com.randioo.market_server.protocol.Heart.CSHeart.Builder subBuilder = com.randioo.market_server.protocol.Heart.CSHeart.newBuilder();
              if (hasCSHeart()) {
                subBuilder.mergeFrom(getCSHeart());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setCSHeart(subBuilder.buildPartial());
              break;
            }
            case 186: {
              com.randioo.market_server.protocol.UserInfo.ActiveInfoRequest.Builder subBuilder = com.randioo.market_server.protocol.UserInfo.ActiveInfoRequest.newBuilder();
              if (hasActiveInfoRequest()) {
                subBuilder.mergeFrom(getActiveInfoRequest());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setActiveInfoRequest(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.market_server.protocol.HeartRequest HeartRequest = 1;
      public boolean hasHeartRequest() {
        return result.hasHeartRequest();
      }
      public com.randioo.market_server.protocol.Heart.HeartRequest getHeartRequest() {
        return result.getHeartRequest();
      }
      public Builder setHeartRequest(com.randioo.market_server.protocol.Heart.HeartRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasHeartRequest = true;
        result.heartRequest_ = value;
        return this;
      }
      public Builder setHeartRequest(com.randioo.market_server.protocol.Heart.HeartRequest.Builder builderForValue) {
        result.hasHeartRequest = true;
        result.heartRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeHeartRequest(com.randioo.market_server.protocol.Heart.HeartRequest value) {
        if (result.hasHeartRequest() &&
            result.heartRequest_ != com.randioo.market_server.protocol.Heart.HeartRequest.getDefaultInstance()) {
          result.heartRequest_ =
            com.randioo.market_server.protocol.Heart.HeartRequest.newBuilder(result.heartRequest_).mergeFrom(value).buildPartial();
        } else {
          result.heartRequest_ = value;
        }
        result.hasHeartRequest = true;
        return this;
      }
      public Builder clearHeartRequest() {
        result.hasHeartRequest = false;
        result.heartRequest_ = com.randioo.market_server.protocol.Heart.HeartRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.LoginCheckAccountRequest LoginCheckAccountRequest = 2;
      public boolean hasLoginCheckAccountRequest() {
        return result.hasLoginCheckAccountRequest();
      }
      public com.randioo.market_server.protocol.Login.LoginCheckAccountRequest getLoginCheckAccountRequest() {
        return result.getLoginCheckAccountRequest();
      }
      public Builder setLoginCheckAccountRequest(com.randioo.market_server.protocol.Login.LoginCheckAccountRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCheckAccountRequest = true;
        result.loginCheckAccountRequest_ = value;
        return this;
      }
      public Builder setLoginCheckAccountRequest(com.randioo.market_server.protocol.Login.LoginCheckAccountRequest.Builder builderForValue) {
        result.hasLoginCheckAccountRequest = true;
        result.loginCheckAccountRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCheckAccountRequest(com.randioo.market_server.protocol.Login.LoginCheckAccountRequest value) {
        if (result.hasLoginCheckAccountRequest() &&
            result.loginCheckAccountRequest_ != com.randioo.market_server.protocol.Login.LoginCheckAccountRequest.getDefaultInstance()) {
          result.loginCheckAccountRequest_ =
            com.randioo.market_server.protocol.Login.LoginCheckAccountRequest.newBuilder(result.loginCheckAccountRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginCheckAccountRequest_ = value;
        }
        result.hasLoginCheckAccountRequest = true;
        return this;
      }
      public Builder clearLoginCheckAccountRequest() {
        result.hasLoginCheckAccountRequest = false;
        result.loginCheckAccountRequest_ = com.randioo.market_server.protocol.Login.LoginCheckAccountRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.GmCmdRequest GmCmdRequest = 3;
      public boolean hasGmCmdRequest() {
        return result.hasGmCmdRequest();
      }
      public com.randioo.market_server.protocol.Gm.GmCmdRequest getGmCmdRequest() {
        return result.getGmCmdRequest();
      }
      public Builder setGmCmdRequest(com.randioo.market_server.protocol.Gm.GmCmdRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGmCmdRequest = true;
        result.gmCmdRequest_ = value;
        return this;
      }
      public Builder setGmCmdRequest(com.randioo.market_server.protocol.Gm.GmCmdRequest.Builder builderForValue) {
        result.hasGmCmdRequest = true;
        result.gmCmdRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeGmCmdRequest(com.randioo.market_server.protocol.Gm.GmCmdRequest value) {
        if (result.hasGmCmdRequest() &&
            result.gmCmdRequest_ != com.randioo.market_server.protocol.Gm.GmCmdRequest.getDefaultInstance()) {
          result.gmCmdRequest_ =
            com.randioo.market_server.protocol.Gm.GmCmdRequest.newBuilder(result.gmCmdRequest_).mergeFrom(value).buildPartial();
        } else {
          result.gmCmdRequest_ = value;
        }
        result.hasGmCmdRequest = true;
        return this;
      }
      public Builder clearGmCmdRequest() {
        result.hasGmCmdRequest = false;
        result.gmCmdRequest_ = com.randioo.market_server.protocol.Gm.GmCmdRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.LoginCreateRoleRequest LoginCreateRoleRequest = 4;
      public boolean hasLoginCreateRoleRequest() {
        return result.hasLoginCreateRoleRequest();
      }
      public com.randioo.market_server.protocol.Login.LoginCreateRoleRequest getLoginCreateRoleRequest() {
        return result.getLoginCreateRoleRequest();
      }
      public Builder setLoginCreateRoleRequest(com.randioo.market_server.protocol.Login.LoginCreateRoleRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginCreateRoleRequest = true;
        result.loginCreateRoleRequest_ = value;
        return this;
      }
      public Builder setLoginCreateRoleRequest(com.randioo.market_server.protocol.Login.LoginCreateRoleRequest.Builder builderForValue) {
        result.hasLoginCreateRoleRequest = true;
        result.loginCreateRoleRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginCreateRoleRequest(com.randioo.market_server.protocol.Login.LoginCreateRoleRequest value) {
        if (result.hasLoginCreateRoleRequest() &&
            result.loginCreateRoleRequest_ != com.randioo.market_server.protocol.Login.LoginCreateRoleRequest.getDefaultInstance()) {
          result.loginCreateRoleRequest_ =
            com.randioo.market_server.protocol.Login.LoginCreateRoleRequest.newBuilder(result.loginCreateRoleRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginCreateRoleRequest_ = value;
        }
        result.hasLoginCreateRoleRequest = true;
        return this;
      }
      public Builder clearLoginCreateRoleRequest() {
        result.hasLoginCreateRoleRequest = false;
        result.loginCreateRoleRequest_ = com.randioo.market_server.protocol.Login.LoginCreateRoleRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.LoginGetRoleDataRequest LoginGetRoleDataRequest = 5;
      public boolean hasLoginGetRoleDataRequest() {
        return result.hasLoginGetRoleDataRequest();
      }
      public com.randioo.market_server.protocol.Login.LoginGetRoleDataRequest getLoginGetRoleDataRequest() {
        return result.getLoginGetRoleDataRequest();
      }
      public Builder setLoginGetRoleDataRequest(com.randioo.market_server.protocol.Login.LoginGetRoleDataRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasLoginGetRoleDataRequest = true;
        result.loginGetRoleDataRequest_ = value;
        return this;
      }
      public Builder setLoginGetRoleDataRequest(com.randioo.market_server.protocol.Login.LoginGetRoleDataRequest.Builder builderForValue) {
        result.hasLoginGetRoleDataRequest = true;
        result.loginGetRoleDataRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeLoginGetRoleDataRequest(com.randioo.market_server.protocol.Login.LoginGetRoleDataRequest value) {
        if (result.hasLoginGetRoleDataRequest() &&
            result.loginGetRoleDataRequest_ != com.randioo.market_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance()) {
          result.loginGetRoleDataRequest_ =
            com.randioo.market_server.protocol.Login.LoginGetRoleDataRequest.newBuilder(result.loginGetRoleDataRequest_).mergeFrom(value).buildPartial();
        } else {
          result.loginGetRoleDataRequest_ = value;
        }
        result.hasLoginGetRoleDataRequest = true;
        return this;
      }
      public Builder clearLoginGetRoleDataRequest() {
        result.hasLoginGetRoleDataRequest = false;
        result.loginGetRoleDataRequest_ = com.randioo.market_server.protocol.Login.LoginGetRoleDataRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.SystemInfoRequest SystemInfoRequest = 6;
      public boolean hasSystemInfoRequest() {
        return result.hasSystemInfoRequest();
      }
      public com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest getSystemInfoRequest() {
        return result.getSystemInfoRequest();
      }
      public Builder setSystemInfoRequest(com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSystemInfoRequest = true;
        result.systemInfoRequest_ = value;
        return this;
      }
      public Builder setSystemInfoRequest(com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest.Builder builderForValue) {
        result.hasSystemInfoRequest = true;
        result.systemInfoRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeSystemInfoRequest(com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest value) {
        if (result.hasSystemInfoRequest() &&
            result.systemInfoRequest_ != com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest.getDefaultInstance()) {
          result.systemInfoRequest_ =
            com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest.newBuilder(result.systemInfoRequest_).mergeFrom(value).buildPartial();
        } else {
          result.systemInfoRequest_ = value;
        }
        result.hasSystemInfoRequest = true;
        return this;
      }
      public Builder clearSystemInfoRequest() {
        result.hasSystemInfoRequest = false;
        result.systemInfoRequest_ = com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.GoodsTyRequest GoodsTyRequest = 7;
      public boolean hasGoodsTyRequest() {
        return result.hasGoodsTyRequest();
      }
      public com.randioo.market_server.protocol.GoodsTy.GoodsTyRequest getGoodsTyRequest() {
        return result.getGoodsTyRequest();
      }
      public Builder setGoodsTyRequest(com.randioo.market_server.protocol.GoodsTy.GoodsTyRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGoodsTyRequest = true;
        result.goodsTyRequest_ = value;
        return this;
      }
      public Builder setGoodsTyRequest(com.randioo.market_server.protocol.GoodsTy.GoodsTyRequest.Builder builderForValue) {
        result.hasGoodsTyRequest = true;
        result.goodsTyRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeGoodsTyRequest(com.randioo.market_server.protocol.GoodsTy.GoodsTyRequest value) {
        if (result.hasGoodsTyRequest() &&
            result.goodsTyRequest_ != com.randioo.market_server.protocol.GoodsTy.GoodsTyRequest.getDefaultInstance()) {
          result.goodsTyRequest_ =
            com.randioo.market_server.protocol.GoodsTy.GoodsTyRequest.newBuilder(result.goodsTyRequest_).mergeFrom(value).buildPartial();
        } else {
          result.goodsTyRequest_ = value;
        }
        result.hasGoodsTyRequest = true;
        return this;
      }
      public Builder clearGoodsTyRequest() {
        result.hasGoodsTyRequest = false;
        result.goodsTyRequest_ = com.randioo.market_server.protocol.GoodsTy.GoodsTyRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.UserInfoRequest UserInfoRequest = 8;
      public boolean hasUserInfoRequest() {
        return result.hasUserInfoRequest();
      }
      public com.randioo.market_server.protocol.UserInfo.UserInfoRequest getUserInfoRequest() {
        return result.getUserInfoRequest();
      }
      public Builder setUserInfoRequest(com.randioo.market_server.protocol.UserInfo.UserInfoRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasUserInfoRequest = true;
        result.userInfoRequest_ = value;
        return this;
      }
      public Builder setUserInfoRequest(com.randioo.market_server.protocol.UserInfo.UserInfoRequest.Builder builderForValue) {
        result.hasUserInfoRequest = true;
        result.userInfoRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeUserInfoRequest(com.randioo.market_server.protocol.UserInfo.UserInfoRequest value) {
        if (result.hasUserInfoRequest() &&
            result.userInfoRequest_ != com.randioo.market_server.protocol.UserInfo.UserInfoRequest.getDefaultInstance()) {
          result.userInfoRequest_ =
            com.randioo.market_server.protocol.UserInfo.UserInfoRequest.newBuilder(result.userInfoRequest_).mergeFrom(value).buildPartial();
        } else {
          result.userInfoRequest_ = value;
        }
        result.hasUserInfoRequest = true;
        return this;
      }
      public Builder clearUserInfoRequest() {
        result.hasUserInfoRequest = false;
        result.userInfoRequest_ = com.randioo.market_server.protocol.UserInfo.UserInfoRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.SellerMyRequest SellerMyRequest = 9;
      public boolean hasSellerMyRequest() {
        return result.hasSellerMyRequest();
      }
      public com.randioo.market_server.protocol.Seller.SellerMyRequest getSellerMyRequest() {
        return result.getSellerMyRequest();
      }
      public Builder setSellerMyRequest(com.randioo.market_server.protocol.Seller.SellerMyRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSellerMyRequest = true;
        result.sellerMyRequest_ = value;
        return this;
      }
      public Builder setSellerMyRequest(com.randioo.market_server.protocol.Seller.SellerMyRequest.Builder builderForValue) {
        result.hasSellerMyRequest = true;
        result.sellerMyRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeSellerMyRequest(com.randioo.market_server.protocol.Seller.SellerMyRequest value) {
        if (result.hasSellerMyRequest() &&
            result.sellerMyRequest_ != com.randioo.market_server.protocol.Seller.SellerMyRequest.getDefaultInstance()) {
          result.sellerMyRequest_ =
            com.randioo.market_server.protocol.Seller.SellerMyRequest.newBuilder(result.sellerMyRequest_).mergeFrom(value).buildPartial();
        } else {
          result.sellerMyRequest_ = value;
        }
        result.hasSellerMyRequest = true;
        return this;
      }
      public Builder clearSellerMyRequest() {
        result.hasSellerMyRequest = false;
        result.sellerMyRequest_ = com.randioo.market_server.protocol.Seller.SellerMyRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.SellerRequest SellerRequest = 10;
      public boolean hasSellerRequest() {
        return result.hasSellerRequest();
      }
      public com.randioo.market_server.protocol.Seller.SellerRequest getSellerRequest() {
        return result.getSellerRequest();
      }
      public Builder setSellerRequest(com.randioo.market_server.protocol.Seller.SellerRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSellerRequest = true;
        result.sellerRequest_ = value;
        return this;
      }
      public Builder setSellerRequest(com.randioo.market_server.protocol.Seller.SellerRequest.Builder builderForValue) {
        result.hasSellerRequest = true;
        result.sellerRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeSellerRequest(com.randioo.market_server.protocol.Seller.SellerRequest value) {
        if (result.hasSellerRequest() &&
            result.sellerRequest_ != com.randioo.market_server.protocol.Seller.SellerRequest.getDefaultInstance()) {
          result.sellerRequest_ =
            com.randioo.market_server.protocol.Seller.SellerRequest.newBuilder(result.sellerRequest_).mergeFrom(value).buildPartial();
        } else {
          result.sellerRequest_ = value;
        }
        result.hasSellerRequest = true;
        return this;
      }
      public Builder clearSellerRequest() {
        result.hasSellerRequest = false;
        result.sellerRequest_ = com.randioo.market_server.protocol.Seller.SellerRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.BuyerRequest BuyerRequest = 11;
      public boolean hasBuyerRequest() {
        return result.hasBuyerRequest();
      }
      public com.randioo.market_server.protocol.Buyer.BuyerRequest getBuyerRequest() {
        return result.getBuyerRequest();
      }
      public Builder setBuyerRequest(com.randioo.market_server.protocol.Buyer.BuyerRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasBuyerRequest = true;
        result.buyerRequest_ = value;
        return this;
      }
      public Builder setBuyerRequest(com.randioo.market_server.protocol.Buyer.BuyerRequest.Builder builderForValue) {
        result.hasBuyerRequest = true;
        result.buyerRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeBuyerRequest(com.randioo.market_server.protocol.Buyer.BuyerRequest value) {
        if (result.hasBuyerRequest() &&
            result.buyerRequest_ != com.randioo.market_server.protocol.Buyer.BuyerRequest.getDefaultInstance()) {
          result.buyerRequest_ =
            com.randioo.market_server.protocol.Buyer.BuyerRequest.newBuilder(result.buyerRequest_).mergeFrom(value).buildPartial();
        } else {
          result.buyerRequest_ = value;
        }
        result.hasBuyerRequest = true;
        return this;
      }
      public Builder clearBuyerRequest() {
        result.hasBuyerRequest = false;
        result.buyerRequest_ = com.randioo.market_server.protocol.Buyer.BuyerRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.RevokeSellerRequest RevokeSellerRequest = 12;
      public boolean hasRevokeSellerRequest() {
        return result.hasRevokeSellerRequest();
      }
      public com.randioo.market_server.protocol.Seller.RevokeSellerRequest getRevokeSellerRequest() {
        return result.getRevokeSellerRequest();
      }
      public Builder setRevokeSellerRequest(com.randioo.market_server.protocol.Seller.RevokeSellerRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasRevokeSellerRequest = true;
        result.revokeSellerRequest_ = value;
        return this;
      }
      public Builder setRevokeSellerRequest(com.randioo.market_server.protocol.Seller.RevokeSellerRequest.Builder builderForValue) {
        result.hasRevokeSellerRequest = true;
        result.revokeSellerRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeRevokeSellerRequest(com.randioo.market_server.protocol.Seller.RevokeSellerRequest value) {
        if (result.hasRevokeSellerRequest() &&
            result.revokeSellerRequest_ != com.randioo.market_server.protocol.Seller.RevokeSellerRequest.getDefaultInstance()) {
          result.revokeSellerRequest_ =
            com.randioo.market_server.protocol.Seller.RevokeSellerRequest.newBuilder(result.revokeSellerRequest_).mergeFrom(value).buildPartial();
        } else {
          result.revokeSellerRequest_ = value;
        }
        result.hasRevokeSellerRequest = true;
        return this;
      }
      public Builder clearRevokeSellerRequest() {
        result.hasRevokeSellerRequest = false;
        result.revokeSellerRequest_ = com.randioo.market_server.protocol.Seller.RevokeSellerRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.GoodsRequest GoodsRequest = 13;
      public boolean hasGoodsRequest() {
        return result.hasGoodsRequest();
      }
      public com.randioo.market_server.protocol.Goods.GoodsRequest getGoodsRequest() {
        return result.getGoodsRequest();
      }
      public Builder setGoodsRequest(com.randioo.market_server.protocol.Goods.GoodsRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasGoodsRequest = true;
        result.goodsRequest_ = value;
        return this;
      }
      public Builder setGoodsRequest(com.randioo.market_server.protocol.Goods.GoodsRequest.Builder builderForValue) {
        result.hasGoodsRequest = true;
        result.goodsRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeGoodsRequest(com.randioo.market_server.protocol.Goods.GoodsRequest value) {
        if (result.hasGoodsRequest() &&
            result.goodsRequest_ != com.randioo.market_server.protocol.Goods.GoodsRequest.getDefaultInstance()) {
          result.goodsRequest_ =
            com.randioo.market_server.protocol.Goods.GoodsRequest.newBuilder(result.goodsRequest_).mergeFrom(value).buildPartial();
        } else {
          result.goodsRequest_ = value;
        }
        result.hasGoodsRequest = true;
        return this;
      }
      public Builder clearGoodsRequest() {
        result.hasGoodsRequest = false;
        result.goodsRequest_ = com.randioo.market_server.protocol.Goods.GoodsRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.DealRequest DealRequest = 14;
      public boolean hasDealRequest() {
        return result.hasDealRequest();
      }
      public com.randioo.market_server.protocol.Deal.DealRequest getDealRequest() {
        return result.getDealRequest();
      }
      public Builder setDealRequest(com.randioo.market_server.protocol.Deal.DealRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasDealRequest = true;
        result.dealRequest_ = value;
        return this;
      }
      public Builder setDealRequest(com.randioo.market_server.protocol.Deal.DealRequest.Builder builderForValue) {
        result.hasDealRequest = true;
        result.dealRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeDealRequest(com.randioo.market_server.protocol.Deal.DealRequest value) {
        if (result.hasDealRequest() &&
            result.dealRequest_ != com.randioo.market_server.protocol.Deal.DealRequest.getDefaultInstance()) {
          result.dealRequest_ =
            com.randioo.market_server.protocol.Deal.DealRequest.newBuilder(result.dealRequest_).mergeFrom(value).buildPartial();
        } else {
          result.dealRequest_ = value;
        }
        result.hasDealRequest = true;
        return this;
      }
      public Builder clearDealRequest() {
        result.hasDealRequest = false;
        result.dealRequest_ = com.randioo.market_server.protocol.Deal.DealRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.KRequest KRequest = 15;
      public boolean hasKRequest() {
        return result.hasKRequest();
      }
      public com.randioo.market_server.protocol.K.KRequest getKRequest() {
        return result.getKRequest();
      }
      public Builder setKRequest(com.randioo.market_server.protocol.K.KRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasKRequest = true;
        result.kRequest_ = value;
        return this;
      }
      public Builder setKRequest(com.randioo.market_server.protocol.K.KRequest.Builder builderForValue) {
        result.hasKRequest = true;
        result.kRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeKRequest(com.randioo.market_server.protocol.K.KRequest value) {
        if (result.hasKRequest() &&
            result.kRequest_ != com.randioo.market_server.protocol.K.KRequest.getDefaultInstance()) {
          result.kRequest_ =
            com.randioo.market_server.protocol.K.KRequest.newBuilder(result.kRequest_).mergeFrom(value).buildPartial();
        } else {
          result.kRequest_ = value;
        }
        result.hasKRequest = true;
        return this;
      }
      public Builder clearKRequest() {
        result.hasKRequest = false;
        result.kRequest_ = com.randioo.market_server.protocol.K.KRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.DayClickRequest DayClickRequest = 16;
      public boolean hasDayClickRequest() {
        return result.hasDayClickRequest();
      }
      public com.randioo.market_server.protocol.K.DayClickRequest getDayClickRequest() {
        return result.getDayClickRequest();
      }
      public Builder setDayClickRequest(com.randioo.market_server.protocol.K.DayClickRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasDayClickRequest = true;
        result.dayClickRequest_ = value;
        return this;
      }
      public Builder setDayClickRequest(com.randioo.market_server.protocol.K.DayClickRequest.Builder builderForValue) {
        result.hasDayClickRequest = true;
        result.dayClickRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeDayClickRequest(com.randioo.market_server.protocol.K.DayClickRequest value) {
        if (result.hasDayClickRequest() &&
            result.dayClickRequest_ != com.randioo.market_server.protocol.K.DayClickRequest.getDefaultInstance()) {
          result.dayClickRequest_ =
            com.randioo.market_server.protocol.K.DayClickRequest.newBuilder(result.dayClickRequest_).mergeFrom(value).buildPartial();
        } else {
          result.dayClickRequest_ = value;
        }
        result.hasDayClickRequest = true;
        return this;
      }
      public Builder clearDayClickRequest() {
        result.hasDayClickRequest = false;
        result.dayClickRequest_ = com.randioo.market_server.protocol.K.DayClickRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.MinkClickRequest MinkClickRequest = 17;
      public boolean hasMinkClickRequest() {
        return result.hasMinkClickRequest();
      }
      public com.randioo.market_server.protocol.K.MinkClickRequest getMinkClickRequest() {
        return result.getMinkClickRequest();
      }
      public Builder setMinkClickRequest(com.randioo.market_server.protocol.K.MinkClickRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasMinkClickRequest = true;
        result.minkClickRequest_ = value;
        return this;
      }
      public Builder setMinkClickRequest(com.randioo.market_server.protocol.K.MinkClickRequest.Builder builderForValue) {
        result.hasMinkClickRequest = true;
        result.minkClickRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeMinkClickRequest(com.randioo.market_server.protocol.K.MinkClickRequest value) {
        if (result.hasMinkClickRequest() &&
            result.minkClickRequest_ != com.randioo.market_server.protocol.K.MinkClickRequest.getDefaultInstance()) {
          result.minkClickRequest_ =
            com.randioo.market_server.protocol.K.MinkClickRequest.newBuilder(result.minkClickRequest_).mergeFrom(value).buildPartial();
        } else {
          result.minkClickRequest_ = value;
        }
        result.hasMinkClickRequest = true;
        return this;
      }
      public Builder clearMinkClickRequest() {
        result.hasMinkClickRequest = false;
        result.minkClickRequest_ = com.randioo.market_server.protocol.K.MinkClickRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.OneMinkRequest OneMinkRequest = 18;
      public boolean hasOneMinkRequest() {
        return result.hasOneMinkRequest();
      }
      public com.randioo.market_server.protocol.K.OneMinkRequest getOneMinkRequest() {
        return result.getOneMinkRequest();
      }
      public Builder setOneMinkRequest(com.randioo.market_server.protocol.K.OneMinkRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasOneMinkRequest = true;
        result.oneMinkRequest_ = value;
        return this;
      }
      public Builder setOneMinkRequest(com.randioo.market_server.protocol.K.OneMinkRequest.Builder builderForValue) {
        result.hasOneMinkRequest = true;
        result.oneMinkRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeOneMinkRequest(com.randioo.market_server.protocol.K.OneMinkRequest value) {
        if (result.hasOneMinkRequest() &&
            result.oneMinkRequest_ != com.randioo.market_server.protocol.K.OneMinkRequest.getDefaultInstance()) {
          result.oneMinkRequest_ =
            com.randioo.market_server.protocol.K.OneMinkRequest.newBuilder(result.oneMinkRequest_).mergeFrom(value).buildPartial();
        } else {
          result.oneMinkRequest_ = value;
        }
        result.hasOneMinkRequest = true;
        return this;
      }
      public Builder clearOneMinkRequest() {
        result.hasOneMinkRequest = false;
        result.oneMinkRequest_ = com.randioo.market_server.protocol.K.OneMinkRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.FifMinkRequest FifMinkRequest = 19;
      public boolean hasFifMinkRequest() {
        return result.hasFifMinkRequest();
      }
      public com.randioo.market_server.protocol.K.FifMinkRequest getFifMinkRequest() {
        return result.getFifMinkRequest();
      }
      public Builder setFifMinkRequest(com.randioo.market_server.protocol.K.FifMinkRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasFifMinkRequest = true;
        result.fifMinkRequest_ = value;
        return this;
      }
      public Builder setFifMinkRequest(com.randioo.market_server.protocol.K.FifMinkRequest.Builder builderForValue) {
        result.hasFifMinkRequest = true;
        result.fifMinkRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeFifMinkRequest(com.randioo.market_server.protocol.K.FifMinkRequest value) {
        if (result.hasFifMinkRequest() &&
            result.fifMinkRequest_ != com.randioo.market_server.protocol.K.FifMinkRequest.getDefaultInstance()) {
          result.fifMinkRequest_ =
            com.randioo.market_server.protocol.K.FifMinkRequest.newBuilder(result.fifMinkRequest_).mergeFrom(value).buildPartial();
        } else {
          result.fifMinkRequest_ = value;
        }
        result.hasFifMinkRequest = true;
        return this;
      }
      public Builder clearFifMinkRequest() {
        result.hasFifMinkRequest = false;
        result.fifMinkRequest_ = com.randioo.market_server.protocol.K.FifMinkRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.ThirtyMinkRequest ThirtyMinkRequest = 20;
      public boolean hasThirtyMinkRequest() {
        return result.hasThirtyMinkRequest();
      }
      public com.randioo.market_server.protocol.K.ThirtyMinkRequest getThirtyMinkRequest() {
        return result.getThirtyMinkRequest();
      }
      public Builder setThirtyMinkRequest(com.randioo.market_server.protocol.K.ThirtyMinkRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasThirtyMinkRequest = true;
        result.thirtyMinkRequest_ = value;
        return this;
      }
      public Builder setThirtyMinkRequest(com.randioo.market_server.protocol.K.ThirtyMinkRequest.Builder builderForValue) {
        result.hasThirtyMinkRequest = true;
        result.thirtyMinkRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeThirtyMinkRequest(com.randioo.market_server.protocol.K.ThirtyMinkRequest value) {
        if (result.hasThirtyMinkRequest() &&
            result.thirtyMinkRequest_ != com.randioo.market_server.protocol.K.ThirtyMinkRequest.getDefaultInstance()) {
          result.thirtyMinkRequest_ =
            com.randioo.market_server.protocol.K.ThirtyMinkRequest.newBuilder(result.thirtyMinkRequest_).mergeFrom(value).buildPartial();
        } else {
          result.thirtyMinkRequest_ = value;
        }
        result.hasThirtyMinkRequest = true;
        return this;
      }
      public Builder clearThirtyMinkRequest() {
        result.hasThirtyMinkRequest = false;
        result.thirtyMinkRequest_ = com.randioo.market_server.protocol.K.ThirtyMinkRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.SixMinkRequest SixMinkRequest = 21;
      public boolean hasSixMinkRequest() {
        return result.hasSixMinkRequest();
      }
      public com.randioo.market_server.protocol.K.SixMinkRequest getSixMinkRequest() {
        return result.getSixMinkRequest();
      }
      public Builder setSixMinkRequest(com.randioo.market_server.protocol.K.SixMinkRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSixMinkRequest = true;
        result.sixMinkRequest_ = value;
        return this;
      }
      public Builder setSixMinkRequest(com.randioo.market_server.protocol.K.SixMinkRequest.Builder builderForValue) {
        result.hasSixMinkRequest = true;
        result.sixMinkRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeSixMinkRequest(com.randioo.market_server.protocol.K.SixMinkRequest value) {
        if (result.hasSixMinkRequest() &&
            result.sixMinkRequest_ != com.randioo.market_server.protocol.K.SixMinkRequest.getDefaultInstance()) {
          result.sixMinkRequest_ =
            com.randioo.market_server.protocol.K.SixMinkRequest.newBuilder(result.sixMinkRequest_).mergeFrom(value).buildPartial();
        } else {
          result.sixMinkRequest_ = value;
        }
        result.hasSixMinkRequest = true;
        return this;
      }
      public Builder clearSixMinkRequest() {
        result.hasSixMinkRequest = false;
        result.sixMinkRequest_ = com.randioo.market_server.protocol.K.SixMinkRequest.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.CSHeart CSHeart = 22;
      public boolean hasCSHeart() {
        return result.hasCSHeart();
      }
      public com.randioo.market_server.protocol.Heart.CSHeart getCSHeart() {
        return result.getCSHeart();
      }
      public Builder setCSHeart(com.randioo.market_server.protocol.Heart.CSHeart value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasCSHeart = true;
        result.cSHeart_ = value;
        return this;
      }
      public Builder setCSHeart(com.randioo.market_server.protocol.Heart.CSHeart.Builder builderForValue) {
        result.hasCSHeart = true;
        result.cSHeart_ = builderForValue.build();
        return this;
      }
      public Builder mergeCSHeart(com.randioo.market_server.protocol.Heart.CSHeart value) {
        if (result.hasCSHeart() &&
            result.cSHeart_ != com.randioo.market_server.protocol.Heart.CSHeart.getDefaultInstance()) {
          result.cSHeart_ =
            com.randioo.market_server.protocol.Heart.CSHeart.newBuilder(result.cSHeart_).mergeFrom(value).buildPartial();
        } else {
          result.cSHeart_ = value;
        }
        result.hasCSHeart = true;
        return this;
      }
      public Builder clearCSHeart() {
        result.hasCSHeart = false;
        result.cSHeart_ = com.randioo.market_server.protocol.Heart.CSHeart.getDefaultInstance();
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.ActiveInfoRequest ActiveInfoRequest = 23;
      public boolean hasActiveInfoRequest() {
        return result.hasActiveInfoRequest();
      }
      public com.randioo.market_server.protocol.UserInfo.ActiveInfoRequest getActiveInfoRequest() {
        return result.getActiveInfoRequest();
      }
      public Builder setActiveInfoRequest(com.randioo.market_server.protocol.UserInfo.ActiveInfoRequest value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasActiveInfoRequest = true;
        result.activeInfoRequest_ = value;
        return this;
      }
      public Builder setActiveInfoRequest(com.randioo.market_server.protocol.UserInfo.ActiveInfoRequest.Builder builderForValue) {
        result.hasActiveInfoRequest = true;
        result.activeInfoRequest_ = builderForValue.build();
        return this;
      }
      public Builder mergeActiveInfoRequest(com.randioo.market_server.protocol.UserInfo.ActiveInfoRequest value) {
        if (result.hasActiveInfoRequest() &&
            result.activeInfoRequest_ != com.randioo.market_server.protocol.UserInfo.ActiveInfoRequest.getDefaultInstance()) {
          result.activeInfoRequest_ =
            com.randioo.market_server.protocol.UserInfo.ActiveInfoRequest.newBuilder(result.activeInfoRequest_).mergeFrom(value).buildPartial();
        } else {
          result.activeInfoRequest_ = value;
        }
        result.hasActiveInfoRequest = true;
        return this;
      }
      public Builder clearActiveInfoRequest() {
        result.hasActiveInfoRequest = false;
        result.activeInfoRequest_ = com.randioo.market_server.protocol.UserInfo.ActiveInfoRequest.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.market_server.protocol.CS)
    }
    
    static {
      defaultInstance = new CS(true);
      com.randioo.market_server.protocol.ClientMessage.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.market_server.protocol.CS)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_market_server_protocol_CS_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_market_server_protocol_CS_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\023ClientMessage.proto\022\"com.randioo.marke" +
      "t_server.protocol\032\013Goods.proto\032\013Login.pr" +
      "oto\032\010Gm.proto\032\014Seller.proto\032\013Buyer.proto" +
      "\032\nDeal.proto\032\016UserInfo.proto\032\rGoodsTy.pr" +
      "oto\032\007K.proto\032\020SystemInfo.proto\032\013Heart.pr" +
      "oto\"\202\016\n\002CS\022F\n\014HeartRequest\030\001 \001(\01320.com.r" +
      "andioo.market_server.protocol.HeartReque" +
      "st\022^\n\030LoginCheckAccountRequest\030\002 \001(\0132<.c" +
      "om.randioo.market_server.protocol.LoginC" +
      "heckAccountRequest\022F\n\014GmCmdRequest\030\003 \001(\013",
      "20.com.randioo.market_server.protocol.Gm" +
      "CmdRequest\022Z\n\026LoginCreateRoleRequest\030\004 \001" +
      "(\0132:.com.randioo.market_server.protocol." +
      "LoginCreateRoleRequest\022\\\n\027LoginGetRoleDa" +
      "taRequest\030\005 \001(\0132;.com.randioo.market_ser" +
      "ver.protocol.LoginGetRoleDataRequest\022P\n\021" +
      "SystemInfoRequest\030\006 \001(\01325.com.randioo.ma" +
      "rket_server.protocol.SystemInfoRequest\022J" +
      "\n\016GoodsTyRequest\030\007 \001(\01322.com.randioo.mar" +
      "ket_server.protocol.GoodsTyRequest\022L\n\017Us",
      "erInfoRequest\030\010 \001(\01323.com.randioo.market" +
      "_server.protocol.UserInfoRequest\022L\n\017Sell" +
      "erMyRequest\030\t \001(\01323.com.randioo.market_s" +
      "erver.protocol.SellerMyRequest\022H\n\rSeller" +
      "Request\030\n \001(\01321.com.randioo.market_serve" +
      "r.protocol.SellerRequest\022F\n\014BuyerRequest" +
      "\030\013 \001(\01320.com.randioo.market_server.proto" +
      "col.BuyerRequest\022T\n\023RevokeSellerRequest\030" +
      "\014 \001(\01327.com.randioo.market_server.protoc" +
      "ol.RevokeSellerRequest\022F\n\014GoodsRequest\030\r",
      " \001(\01320.com.randioo.market_server.protoco" +
      "l.GoodsRequest\022D\n\013DealRequest\030\016 \001(\0132/.co" +
      "m.randioo.market_server.protocol.DealReq" +
      "uest\022>\n\010KRequest\030\017 \001(\0132,.com.randioo.mar" +
      "ket_server.protocol.KRequest\022L\n\017DayClick" +
      "Request\030\020 \001(\01323.com.randioo.market_serve" +
      "r.protocol.DayClickRequest\022N\n\020MinkClickR" +
      "equest\030\021 \001(\01324.com.randioo.market_server" +
      ".protocol.MinkClickRequest\022J\n\016OneMinkReq" +
      "uest\030\022 \001(\01322.com.randioo.market_server.p",
      "rotocol.OneMinkRequest\022J\n\016FifMinkRequest" +
      "\030\023 \001(\01322.com.randioo.market_server.proto" +
      "col.FifMinkRequest\022P\n\021ThirtyMinkRequest\030" +
      "\024 \001(\01325.com.randioo.market_server.protoc" +
      "ol.ThirtyMinkRequest\022J\n\016SixMinkRequest\030\025" +
      " \001(\01322.com.randioo.market_server.protoco" +
      "l.SixMinkRequest\022<\n\007CSHeart\030\026 \001(\0132+.com." +
      "randioo.market_server.protocol.CSHeart\022P" +
      "\n\021ActiveInfoRequest\030\027 \001(\01325.com.randioo." +
      "market_server.protocol.ActiveInfoRequest"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_market_server_protocol_CS_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_market_server_protocol_CS_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_market_server_protocol_CS_descriptor,
              new java.lang.String[] { "HeartRequest", "LoginCheckAccountRequest", "GmCmdRequest", "LoginCreateRoleRequest", "LoginGetRoleDataRequest", "SystemInfoRequest", "GoodsTyRequest", "UserInfoRequest", "SellerMyRequest", "SellerRequest", "BuyerRequest", "RevokeSellerRequest", "GoodsRequest", "DealRequest", "KRequest", "DayClickRequest", "MinkClickRequest", "OneMinkRequest", "FifMinkRequest", "ThirtyMinkRequest", "SixMinkRequest", "CSHeart", "ActiveInfoRequest", },
              com.randioo.market_server.protocol.ClientMessage.CS.class,
              com.randioo.market_server.protocol.ClientMessage.CS.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.market_server.protocol.Goods.getDescriptor(),
          com.randioo.market_server.protocol.Login.getDescriptor(),
          com.randioo.market_server.protocol.Gm.getDescriptor(),
          com.randioo.market_server.protocol.Seller.getDescriptor(),
          com.randioo.market_server.protocol.Buyer.getDescriptor(),
          com.randioo.market_server.protocol.Deal.getDescriptor(),
          com.randioo.market_server.protocol.UserInfo.getDescriptor(),
          com.randioo.market_server.protocol.GoodsTy.getDescriptor(),
          com.randioo.market_server.protocol.K.getDescriptor(),
          com.randioo.market_server.protocol.SystemInfo.getDescriptor(),
          com.randioo.market_server.protocol.Heart.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
