// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Deal.proto

package com.randioo.market_server.protocol;

public final class Deal {
  private Deal() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class DealRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use DealRequest.newBuilder() to construct.
    private DealRequest() {
      initFields();
    }
    private DealRequest(boolean noInit) {}
    
    private static final DealRequest defaultInstance;
    public static DealRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public DealRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.market_server.protocol.Deal.internal_static_com_randioo_market_server_protocol_DealRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.market_server.protocol.Deal.internal_static_com_randioo_market_server_protocol_DealRequest_fieldAccessorTable;
    }
    
    // optional string type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private boolean hasType;
    private java.lang.String type_ = "";
    public boolean hasType() { return hasType; }
    public java.lang.String getType() { return type_; }
    
    // optional int32 startNum = 2;
    public static final int STARTNUM_FIELD_NUMBER = 2;
    private boolean hasStartNum;
    private int startNum_ = 0;
    public boolean hasStartNum() { return hasStartNum; }
    public int getStartNum() { return startNum_; }
    
    // optional int32 count = 3;
    public static final int COUNT_FIELD_NUMBER = 3;
    private boolean hasCount;
    private int count_ = 0;
    public boolean hasCount() { return hasCount; }
    public int getCount() { return count_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasType()) {
        output.writeString(1, getType());
      }
      if (hasStartNum()) {
        output.writeInt32(2, getStartNum());
      }
      if (hasCount()) {
        output.writeInt32(3, getCount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getType());
      }
      if (hasStartNum()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, getStartNum());
      }
      if (hasCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(3, getCount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.market_server.protocol.Deal.DealRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Deal.DealRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Deal.DealRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Deal.DealRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Deal.DealRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Deal.DealRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Deal.DealRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Deal.DealRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Deal.DealRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Deal.DealRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.market_server.protocol.Deal.DealRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.market_server.protocol.Deal.DealRequest result;
      
      // Construct using com.randioo.market_server.protocol.Deal.DealRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.market_server.protocol.Deal.DealRequest();
        return builder;
      }
      
      protected com.randioo.market_server.protocol.Deal.DealRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.market_server.protocol.Deal.DealRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.market_server.protocol.Deal.DealRequest.getDescriptor();
      }
      
      public com.randioo.market_server.protocol.Deal.DealRequest getDefaultInstanceForType() {
        return com.randioo.market_server.protocol.Deal.DealRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.market_server.protocol.Deal.DealRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.market_server.protocol.Deal.DealRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.market_server.protocol.Deal.DealRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.market_server.protocol.Deal.DealRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.market_server.protocol.Deal.DealRequest) {
          return mergeFrom((com.randioo.market_server.protocol.Deal.DealRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.market_server.protocol.Deal.DealRequest other) {
        if (other == com.randioo.market_server.protocol.Deal.DealRequest.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasStartNum()) {
          setStartNum(other.getStartNum());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setType(input.readString());
              break;
            }
            case 16: {
              setStartNum(input.readInt32());
              break;
            }
            case 24: {
              setCount(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional string type = 1;
      public boolean hasType() {
        return result.hasType();
      }
      public java.lang.String getType() {
        return result.getType();
      }
      public Builder setType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = getDefaultInstance().getType();
        return this;
      }
      
      // optional int32 startNum = 2;
      public boolean hasStartNum() {
        return result.hasStartNum();
      }
      public int getStartNum() {
        return result.getStartNum();
      }
      public Builder setStartNum(int value) {
        result.hasStartNum = true;
        result.startNum_ = value;
        return this;
      }
      public Builder clearStartNum() {
        result.hasStartNum = false;
        result.startNum_ = 0;
        return this;
      }
      
      // optional int32 count = 3;
      public boolean hasCount() {
        return result.hasCount();
      }
      public int getCount() {
        return result.getCount();
      }
      public Builder setCount(int value) {
        result.hasCount = true;
        result.count_ = value;
        return this;
      }
      public Builder clearCount() {
        result.hasCount = false;
        result.count_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.market_server.protocol.DealRequest)
    }
    
    static {
      defaultInstance = new DealRequest(true);
      com.randioo.market_server.protocol.Deal.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.market_server.protocol.DealRequest)
  }
  
  public static final class DealResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use DealResponse.newBuilder() to construct.
    private DealResponse() {
      initFields();
    }
    private DealResponse(boolean noInit) {}
    
    private static final DealResponse defaultInstance;
    public static DealResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public DealResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.market_server.protocol.Deal.internal_static_com_randioo_market_server_protocol_DealResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.market_server.protocol.Deal.internal_static_com_randioo_market_server_protocol_DealResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    // repeated .com.randioo.market_server.protocol.TradingData TradingData = 2;
    public static final int TRADINGDATA_FIELD_NUMBER = 2;
    private java.util.List<com.randioo.market_server.protocol.Entity.TradingData> tradingData_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.market_server.protocol.Entity.TradingData> getTradingDataList() {
      return tradingData_;
    }
    public int getTradingDataCount() { return tradingData_.size(); }
    public com.randioo.market_server.protocol.Entity.TradingData getTradingData(int index) {
      return tradingData_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      for (com.randioo.market_server.protocol.Entity.TradingData element : getTradingDataList()) {
        output.writeMessage(2, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      for (com.randioo.market_server.protocol.Entity.TradingData element : getTradingDataList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.market_server.protocol.Deal.DealResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Deal.DealResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Deal.DealResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Deal.DealResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Deal.DealResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Deal.DealResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Deal.DealResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Deal.DealResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Deal.DealResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Deal.DealResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.market_server.protocol.Deal.DealResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.market_server.protocol.Deal.DealResponse result;
      
      // Construct using com.randioo.market_server.protocol.Deal.DealResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.market_server.protocol.Deal.DealResponse();
        return builder;
      }
      
      protected com.randioo.market_server.protocol.Deal.DealResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.market_server.protocol.Deal.DealResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.market_server.protocol.Deal.DealResponse.getDescriptor();
      }
      
      public com.randioo.market_server.protocol.Deal.DealResponse getDefaultInstanceForType() {
        return com.randioo.market_server.protocol.Deal.DealResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.market_server.protocol.Deal.DealResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.market_server.protocol.Deal.DealResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.market_server.protocol.Deal.DealResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.tradingData_ != java.util.Collections.EMPTY_LIST) {
          result.tradingData_ =
            java.util.Collections.unmodifiableList(result.tradingData_);
        }
        com.randioo.market_server.protocol.Deal.DealResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.market_server.protocol.Deal.DealResponse) {
          return mergeFrom((com.randioo.market_server.protocol.Deal.DealResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.market_server.protocol.Deal.DealResponse other) {
        if (other == com.randioo.market_server.protocol.Deal.DealResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (!other.tradingData_.isEmpty()) {
          if (result.tradingData_.isEmpty()) {
            result.tradingData_ = new java.util.ArrayList<com.randioo.market_server.protocol.Entity.TradingData>();
          }
          result.tradingData_.addAll(other.tradingData_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
            case 18: {
              com.randioo.market_server.protocol.Entity.TradingData.Builder subBuilder = com.randioo.market_server.protocol.Entity.TradingData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addTradingData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // repeated .com.randioo.market_server.protocol.TradingData TradingData = 2;
      public java.util.List<com.randioo.market_server.protocol.Entity.TradingData> getTradingDataList() {
        return java.util.Collections.unmodifiableList(result.tradingData_);
      }
      public int getTradingDataCount() {
        return result.getTradingDataCount();
      }
      public com.randioo.market_server.protocol.Entity.TradingData getTradingData(int index) {
        return result.getTradingData(index);
      }
      public Builder setTradingData(int index, com.randioo.market_server.protocol.Entity.TradingData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.tradingData_.set(index, value);
        return this;
      }
      public Builder setTradingData(int index, com.randioo.market_server.protocol.Entity.TradingData.Builder builderForValue) {
        result.tradingData_.set(index, builderForValue.build());
        return this;
      }
      public Builder addTradingData(com.randioo.market_server.protocol.Entity.TradingData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.tradingData_.isEmpty()) {
          result.tradingData_ = new java.util.ArrayList<com.randioo.market_server.protocol.Entity.TradingData>();
        }
        result.tradingData_.add(value);
        return this;
      }
      public Builder addTradingData(com.randioo.market_server.protocol.Entity.TradingData.Builder builderForValue) {
        if (result.tradingData_.isEmpty()) {
          result.tradingData_ = new java.util.ArrayList<com.randioo.market_server.protocol.Entity.TradingData>();
        }
        result.tradingData_.add(builderForValue.build());
        return this;
      }
      public Builder addAllTradingData(
          java.lang.Iterable<? extends com.randioo.market_server.protocol.Entity.TradingData> values) {
        if (result.tradingData_.isEmpty()) {
          result.tradingData_ = new java.util.ArrayList<com.randioo.market_server.protocol.Entity.TradingData>();
        }
        super.addAll(values, result.tradingData_);
        return this;
      }
      public Builder clearTradingData() {
        result.tradingData_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.market_server.protocol.DealResponse)
    }
    
    static {
      defaultInstance = new DealResponse(true);
      com.randioo.market_server.protocol.Deal.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.market_server.protocol.DealResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_market_server_protocol_DealRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_market_server_protocol_DealRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_market_server_protocol_DealResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_market_server_protocol_DealResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\nDeal.proto\022\"com.randioo.market_server." +
      "protocol\032\014Entity.proto\"<\n\013DealRequest\022\014\n" +
      "\004type\030\001 \001(\t\022\020\n\010startNum\030\002 \001(\005\022\r\n\005count\030\003" +
      " \001(\005\"j\n\014DealResponse\022\024\n\terrorCode\030\001 \001(\005:" +
      "\0011\022D\n\013TradingData\030\002 \003(\0132/.com.randioo.ma" +
      "rket_server.protocol.TradingData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_market_server_protocol_DealRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_market_server_protocol_DealRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_market_server_protocol_DealRequest_descriptor,
              new java.lang.String[] { "Type", "StartNum", "Count", },
              com.randioo.market_server.protocol.Deal.DealRequest.class,
              com.randioo.market_server.protocol.Deal.DealRequest.Builder.class);
          internal_static_com_randioo_market_server_protocol_DealResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_market_server_protocol_DealResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_market_server_protocol_DealResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "TradingData", },
              com.randioo.market_server.protocol.Deal.DealResponse.class,
              com.randioo.market_server.protocol.Deal.DealResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.market_server.protocol.Entity.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
