// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: Seller.proto

package com.randioo.market_server.protocol;

public final class Seller {
  private Seller() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class SellerRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use SellerRequest.newBuilder() to construct.
    private SellerRequest() {
      initFields();
    }
    private SellerRequest(boolean noInit) {}
    
    private static final SellerRequest defaultInstance;
    public static SellerRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public SellerRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.market_server.protocol.Seller.internal_static_com_randioo_market_server_protocol_SellerRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.market_server.protocol.Seller.internal_static_com_randioo_market_server_protocol_SellerRequest_fieldAccessorTable;
    }
    
    // optional .com.randioo.market_server.protocol.SellerInfoData SellerInfoData = 1;
    public static final int SELLERINFODATA_FIELD_NUMBER = 1;
    private boolean hasSellerInfoData;
    private com.randioo.market_server.protocol.Entity.SellerInfoData sellerInfoData_;
    public boolean hasSellerInfoData() { return hasSellerInfoData; }
    public com.randioo.market_server.protocol.Entity.SellerInfoData getSellerInfoData() { return sellerInfoData_; }
    
    private void initFields() {
      sellerInfoData_ = com.randioo.market_server.protocol.Entity.SellerInfoData.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasSellerInfoData()) {
        output.writeMessage(1, getSellerInfoData());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasSellerInfoData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, getSellerInfoData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.market_server.protocol.Seller.SellerRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Seller.SellerRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Seller.SellerRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.market_server.protocol.Seller.SellerRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.market_server.protocol.Seller.SellerRequest result;
      
      // Construct using com.randioo.market_server.protocol.Seller.SellerRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.market_server.protocol.Seller.SellerRequest();
        return builder;
      }
      
      protected com.randioo.market_server.protocol.Seller.SellerRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.market_server.protocol.Seller.SellerRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.market_server.protocol.Seller.SellerRequest.getDescriptor();
      }
      
      public com.randioo.market_server.protocol.Seller.SellerRequest getDefaultInstanceForType() {
        return com.randioo.market_server.protocol.Seller.SellerRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.market_server.protocol.Seller.SellerRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.market_server.protocol.Seller.SellerRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.market_server.protocol.Seller.SellerRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.market_server.protocol.Seller.SellerRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.market_server.protocol.Seller.SellerRequest) {
          return mergeFrom((com.randioo.market_server.protocol.Seller.SellerRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.market_server.protocol.Seller.SellerRequest other) {
        if (other == com.randioo.market_server.protocol.Seller.SellerRequest.getDefaultInstance()) return this;
        if (other.hasSellerInfoData()) {
          mergeSellerInfoData(other.getSellerInfoData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.market_server.protocol.Entity.SellerInfoData.Builder subBuilder = com.randioo.market_server.protocol.Entity.SellerInfoData.newBuilder();
              if (hasSellerInfoData()) {
                subBuilder.mergeFrom(getSellerInfoData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSellerInfoData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional .com.randioo.market_server.protocol.SellerInfoData SellerInfoData = 1;
      public boolean hasSellerInfoData() {
        return result.hasSellerInfoData();
      }
      public com.randioo.market_server.protocol.Entity.SellerInfoData getSellerInfoData() {
        return result.getSellerInfoData();
      }
      public Builder setSellerInfoData(com.randioo.market_server.protocol.Entity.SellerInfoData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSellerInfoData = true;
        result.sellerInfoData_ = value;
        return this;
      }
      public Builder setSellerInfoData(com.randioo.market_server.protocol.Entity.SellerInfoData.Builder builderForValue) {
        result.hasSellerInfoData = true;
        result.sellerInfoData_ = builderForValue.build();
        return this;
      }
      public Builder mergeSellerInfoData(com.randioo.market_server.protocol.Entity.SellerInfoData value) {
        if (result.hasSellerInfoData() &&
            result.sellerInfoData_ != com.randioo.market_server.protocol.Entity.SellerInfoData.getDefaultInstance()) {
          result.sellerInfoData_ =
            com.randioo.market_server.protocol.Entity.SellerInfoData.newBuilder(result.sellerInfoData_).mergeFrom(value).buildPartial();
        } else {
          result.sellerInfoData_ = value;
        }
        result.hasSellerInfoData = true;
        return this;
      }
      public Builder clearSellerInfoData() {
        result.hasSellerInfoData = false;
        result.sellerInfoData_ = com.randioo.market_server.protocol.Entity.SellerInfoData.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.market_server.protocol.SellerRequest)
    }
    
    static {
      defaultInstance = new SellerRequest(true);
      com.randioo.market_server.protocol.Seller.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.market_server.protocol.SellerRequest)
  }
  
  public static final class SellerResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use SellerResponse.newBuilder() to construct.
    private SellerResponse() {
      initFields();
    }
    private SellerResponse(boolean noInit) {}
    
    private static final SellerResponse defaultInstance;
    public static SellerResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public SellerResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.market_server.protocol.Seller.internal_static_com_randioo_market_server_protocol_SellerResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.market_server.protocol.Seller.internal_static_com_randioo_market_server_protocol_SellerResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    // optional .com.randioo.market_server.protocol.SellerData sellerData = 2;
    public static final int SELLERDATA_FIELD_NUMBER = 2;
    private boolean hasSellerData;
    private com.randioo.market_server.protocol.Entity.SellerData sellerData_;
    public boolean hasSellerData() { return hasSellerData; }
    public com.randioo.market_server.protocol.Entity.SellerData getSellerData() { return sellerData_; }
    
    private void initFields() {
      sellerData_ = com.randioo.market_server.protocol.Entity.SellerData.getDefaultInstance();
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      if (hasSellerData()) {
        output.writeMessage(2, getSellerData());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      if (hasSellerData()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getSellerData());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.market_server.protocol.Seller.SellerResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Seller.SellerResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Seller.SellerResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.market_server.protocol.Seller.SellerResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.market_server.protocol.Seller.SellerResponse result;
      
      // Construct using com.randioo.market_server.protocol.Seller.SellerResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.market_server.protocol.Seller.SellerResponse();
        return builder;
      }
      
      protected com.randioo.market_server.protocol.Seller.SellerResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.market_server.protocol.Seller.SellerResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.market_server.protocol.Seller.SellerResponse.getDescriptor();
      }
      
      public com.randioo.market_server.protocol.Seller.SellerResponse getDefaultInstanceForType() {
        return com.randioo.market_server.protocol.Seller.SellerResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.market_server.protocol.Seller.SellerResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.market_server.protocol.Seller.SellerResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.market_server.protocol.Seller.SellerResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.market_server.protocol.Seller.SellerResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.market_server.protocol.Seller.SellerResponse) {
          return mergeFrom((com.randioo.market_server.protocol.Seller.SellerResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.market_server.protocol.Seller.SellerResponse other) {
        if (other == com.randioo.market_server.protocol.Seller.SellerResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasSellerData()) {
          mergeSellerData(other.getSellerData());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
            case 18: {
              com.randioo.market_server.protocol.Entity.SellerData.Builder subBuilder = com.randioo.market_server.protocol.Entity.SellerData.newBuilder();
              if (hasSellerData()) {
                subBuilder.mergeFrom(getSellerData());
              }
              input.readMessage(subBuilder, extensionRegistry);
              setSellerData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // optional .com.randioo.market_server.protocol.SellerData sellerData = 2;
      public boolean hasSellerData() {
        return result.hasSellerData();
      }
      public com.randioo.market_server.protocol.Entity.SellerData getSellerData() {
        return result.getSellerData();
      }
      public Builder setSellerData(com.randioo.market_server.protocol.Entity.SellerData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.hasSellerData = true;
        result.sellerData_ = value;
        return this;
      }
      public Builder setSellerData(com.randioo.market_server.protocol.Entity.SellerData.Builder builderForValue) {
        result.hasSellerData = true;
        result.sellerData_ = builderForValue.build();
        return this;
      }
      public Builder mergeSellerData(com.randioo.market_server.protocol.Entity.SellerData value) {
        if (result.hasSellerData() &&
            result.sellerData_ != com.randioo.market_server.protocol.Entity.SellerData.getDefaultInstance()) {
          result.sellerData_ =
            com.randioo.market_server.protocol.Entity.SellerData.newBuilder(result.sellerData_).mergeFrom(value).buildPartial();
        } else {
          result.sellerData_ = value;
        }
        result.hasSellerData = true;
        return this;
      }
      public Builder clearSellerData() {
        result.hasSellerData = false;
        result.sellerData_ = com.randioo.market_server.protocol.Entity.SellerData.getDefaultInstance();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.market_server.protocol.SellerResponse)
    }
    
    static {
      defaultInstance = new SellerResponse(true);
      com.randioo.market_server.protocol.Seller.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.market_server.protocol.SellerResponse)
  }
  
  public static final class RevokeSellerRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use RevokeSellerRequest.newBuilder() to construct.
    private RevokeSellerRequest() {
      initFields();
    }
    private RevokeSellerRequest(boolean noInit) {}
    
    private static final RevokeSellerRequest defaultInstance;
    public static RevokeSellerRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public RevokeSellerRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.market_server.protocol.Seller.internal_static_com_randioo_market_server_protocol_RevokeSellerRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.market_server.protocol.Seller.internal_static_com_randioo_market_server_protocol_RevokeSellerRequest_fieldAccessorTable;
    }
    
    // optional string type = 1;
    public static final int TYPE_FIELD_NUMBER = 1;
    private boolean hasType;
    private java.lang.String type_ = "";
    public boolean hasType() { return hasType; }
    public java.lang.String getType() { return type_; }
    
    // optional string price = 2;
    public static final int PRICE_FIELD_NUMBER = 2;
    private boolean hasPrice;
    private java.lang.String price_ = "";
    public boolean hasPrice() { return hasPrice; }
    public java.lang.String getPrice() { return price_; }
    
    // optional string sellAccount = 3;
    public static final int SELLACCOUNT_FIELD_NUMBER = 3;
    private boolean hasSellAccount;
    private java.lang.String sellAccount_ = "";
    public boolean hasSellAccount() { return hasSellAccount; }
    public java.lang.String getSellAccount() { return sellAccount_; }
    
    // optional int32 sellId = 4;
    public static final int SELLID_FIELD_NUMBER = 4;
    private boolean hasSellId;
    private int sellId_ = 0;
    public boolean hasSellId() { return hasSellId; }
    public int getSellId() { return sellId_; }
    
    // optional int32 count = 5;
    public static final int COUNT_FIELD_NUMBER = 5;
    private boolean hasCount;
    private int count_ = 0;
    public boolean hasCount() { return hasCount; }
    public int getCount() { return count_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasType()) {
        output.writeString(1, getType());
      }
      if (hasPrice()) {
        output.writeString(2, getPrice());
      }
      if (hasSellAccount()) {
        output.writeString(3, getSellAccount());
      }
      if (hasSellId()) {
        output.writeInt32(4, getSellId());
      }
      if (hasCount()) {
        output.writeInt32(5, getCount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasType()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getType());
      }
      if (hasPrice()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getPrice());
      }
      if (hasSellAccount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getSellAccount());
      }
      if (hasSellId()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(4, getSellId());
      }
      if (hasCount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(5, getCount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.market_server.protocol.Seller.RevokeSellerRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.market_server.protocol.Seller.RevokeSellerRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.market_server.protocol.Seller.RevokeSellerRequest result;
      
      // Construct using com.randioo.market_server.protocol.Seller.RevokeSellerRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.market_server.protocol.Seller.RevokeSellerRequest();
        return builder;
      }
      
      protected com.randioo.market_server.protocol.Seller.RevokeSellerRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.market_server.protocol.Seller.RevokeSellerRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.market_server.protocol.Seller.RevokeSellerRequest.getDescriptor();
      }
      
      public com.randioo.market_server.protocol.Seller.RevokeSellerRequest getDefaultInstanceForType() {
        return com.randioo.market_server.protocol.Seller.RevokeSellerRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.market_server.protocol.Seller.RevokeSellerRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.market_server.protocol.Seller.RevokeSellerRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.market_server.protocol.Seller.RevokeSellerRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.market_server.protocol.Seller.RevokeSellerRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.market_server.protocol.Seller.RevokeSellerRequest) {
          return mergeFrom((com.randioo.market_server.protocol.Seller.RevokeSellerRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.market_server.protocol.Seller.RevokeSellerRequest other) {
        if (other == com.randioo.market_server.protocol.Seller.RevokeSellerRequest.getDefaultInstance()) return this;
        if (other.hasType()) {
          setType(other.getType());
        }
        if (other.hasPrice()) {
          setPrice(other.getPrice());
        }
        if (other.hasSellAccount()) {
          setSellAccount(other.getSellAccount());
        }
        if (other.hasSellId()) {
          setSellId(other.getSellId());
        }
        if (other.hasCount()) {
          setCount(other.getCount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setType(input.readString());
              break;
            }
            case 18: {
              setPrice(input.readString());
              break;
            }
            case 26: {
              setSellAccount(input.readString());
              break;
            }
            case 32: {
              setSellId(input.readInt32());
              break;
            }
            case 40: {
              setCount(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional string type = 1;
      public boolean hasType() {
        return result.hasType();
      }
      public java.lang.String getType() {
        return result.getType();
      }
      public Builder setType(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasType = true;
        result.type_ = value;
        return this;
      }
      public Builder clearType() {
        result.hasType = false;
        result.type_ = getDefaultInstance().getType();
        return this;
      }
      
      // optional string price = 2;
      public boolean hasPrice() {
        return result.hasPrice();
      }
      public java.lang.String getPrice() {
        return result.getPrice();
      }
      public Builder setPrice(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasPrice = true;
        result.price_ = value;
        return this;
      }
      public Builder clearPrice() {
        result.hasPrice = false;
        result.price_ = getDefaultInstance().getPrice();
        return this;
      }
      
      // optional string sellAccount = 3;
      public boolean hasSellAccount() {
        return result.hasSellAccount();
      }
      public java.lang.String getSellAccount() {
        return result.getSellAccount();
      }
      public Builder setSellAccount(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSellAccount = true;
        result.sellAccount_ = value;
        return this;
      }
      public Builder clearSellAccount() {
        result.hasSellAccount = false;
        result.sellAccount_ = getDefaultInstance().getSellAccount();
        return this;
      }
      
      // optional int32 sellId = 4;
      public boolean hasSellId() {
        return result.hasSellId();
      }
      public int getSellId() {
        return result.getSellId();
      }
      public Builder setSellId(int value) {
        result.hasSellId = true;
        result.sellId_ = value;
        return this;
      }
      public Builder clearSellId() {
        result.hasSellId = false;
        result.sellId_ = 0;
        return this;
      }
      
      // optional int32 count = 5;
      public boolean hasCount() {
        return result.hasCount();
      }
      public int getCount() {
        return result.getCount();
      }
      public Builder setCount(int value) {
        result.hasCount = true;
        result.count_ = value;
        return this;
      }
      public Builder clearCount() {
        result.hasCount = false;
        result.count_ = 0;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.market_server.protocol.RevokeSellerRequest)
    }
    
    static {
      defaultInstance = new RevokeSellerRequest(true);
      com.randioo.market_server.protocol.Seller.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.market_server.protocol.RevokeSellerRequest)
  }
  
  public static final class RevokeSellerResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use RevokeSellerResponse.newBuilder() to construct.
    private RevokeSellerResponse() {
      initFields();
    }
    private RevokeSellerResponse(boolean noInit) {}
    
    private static final RevokeSellerResponse defaultInstance;
    public static RevokeSellerResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public RevokeSellerResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.market_server.protocol.Seller.internal_static_com_randioo_market_server_protocol_RevokeSellerResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.market_server.protocol.Seller.internal_static_com_randioo_market_server_protocol_RevokeSellerResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    // optional string freeback = 2;
    public static final int FREEBACK_FIELD_NUMBER = 2;
    private boolean hasFreeback;
    private java.lang.String freeback_ = "";
    public boolean hasFreeback() { return hasFreeback; }
    public java.lang.String getFreeback() { return freeback_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      if (hasFreeback()) {
        output.writeString(2, getFreeback());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      if (hasFreeback()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getFreeback());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.market_server.protocol.Seller.RevokeSellerResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.RevokeSellerResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.market_server.protocol.Seller.RevokeSellerResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.market_server.protocol.Seller.RevokeSellerResponse result;
      
      // Construct using com.randioo.market_server.protocol.Seller.RevokeSellerResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.market_server.protocol.Seller.RevokeSellerResponse();
        return builder;
      }
      
      protected com.randioo.market_server.protocol.Seller.RevokeSellerResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.market_server.protocol.Seller.RevokeSellerResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.market_server.protocol.Seller.RevokeSellerResponse.getDescriptor();
      }
      
      public com.randioo.market_server.protocol.Seller.RevokeSellerResponse getDefaultInstanceForType() {
        return com.randioo.market_server.protocol.Seller.RevokeSellerResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.market_server.protocol.Seller.RevokeSellerResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.market_server.protocol.Seller.RevokeSellerResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.market_server.protocol.Seller.RevokeSellerResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.market_server.protocol.Seller.RevokeSellerResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.market_server.protocol.Seller.RevokeSellerResponse) {
          return mergeFrom((com.randioo.market_server.protocol.Seller.RevokeSellerResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.market_server.protocol.Seller.RevokeSellerResponse other) {
        if (other == com.randioo.market_server.protocol.Seller.RevokeSellerResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasFreeback()) {
          setFreeback(other.getFreeback());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
            case 18: {
              setFreeback(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // optional string freeback = 2;
      public boolean hasFreeback() {
        return result.hasFreeback();
      }
      public java.lang.String getFreeback() {
        return result.getFreeback();
      }
      public Builder setFreeback(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasFreeback = true;
        result.freeback_ = value;
        return this;
      }
      public Builder clearFreeback() {
        result.hasFreeback = false;
        result.freeback_ = getDefaultInstance().getFreeback();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.market_server.protocol.RevokeSellerResponse)
    }
    
    static {
      defaultInstance = new RevokeSellerResponse(true);
      com.randioo.market_server.protocol.Seller.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.market_server.protocol.RevokeSellerResponse)
  }
  
  public static final class SellerMyRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use SellerMyRequest.newBuilder() to construct.
    private SellerMyRequest() {
      initFields();
    }
    private SellerMyRequest(boolean noInit) {}
    
    private static final SellerMyRequest defaultInstance;
    public static SellerMyRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public SellerMyRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.market_server.protocol.Seller.internal_static_com_randioo_market_server_protocol_SellerMyRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.market_server.protocol.Seller.internal_static_com_randioo_market_server_protocol_SellerMyRequest_fieldAccessorTable;
    }
    
    // optional string account = 1;
    public static final int ACCOUNT_FIELD_NUMBER = 1;
    private boolean hasAccount;
    private java.lang.String account_ = "";
    public boolean hasAccount() { return hasAccount; }
    public java.lang.String getAccount() { return account_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasAccount()) {
        output.writeString(1, getAccount());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasAccount()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(1, getAccount());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.market_server.protocol.Seller.SellerMyRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.market_server.protocol.Seller.SellerMyRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.market_server.protocol.Seller.SellerMyRequest result;
      
      // Construct using com.randioo.market_server.protocol.Seller.SellerMyRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.market_server.protocol.Seller.SellerMyRequest();
        return builder;
      }
      
      protected com.randioo.market_server.protocol.Seller.SellerMyRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.market_server.protocol.Seller.SellerMyRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.market_server.protocol.Seller.SellerMyRequest.getDescriptor();
      }
      
      public com.randioo.market_server.protocol.Seller.SellerMyRequest getDefaultInstanceForType() {
        return com.randioo.market_server.protocol.Seller.SellerMyRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.market_server.protocol.Seller.SellerMyRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.market_server.protocol.Seller.SellerMyRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.market_server.protocol.Seller.SellerMyRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.market_server.protocol.Seller.SellerMyRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.market_server.protocol.Seller.SellerMyRequest) {
          return mergeFrom((com.randioo.market_server.protocol.Seller.SellerMyRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.market_server.protocol.Seller.SellerMyRequest other) {
        if (other == com.randioo.market_server.protocol.Seller.SellerMyRequest.getDefaultInstance()) return this;
        if (other.hasAccount()) {
          setAccount(other.getAccount());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              setAccount(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional string account = 1;
      public boolean hasAccount() {
        return result.hasAccount();
      }
      public java.lang.String getAccount() {
        return result.getAccount();
      }
      public Builder setAccount(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasAccount = true;
        result.account_ = value;
        return this;
      }
      public Builder clearAccount() {
        result.hasAccount = false;
        result.account_ = getDefaultInstance().getAccount();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.market_server.protocol.SellerMyRequest)
    }
    
    static {
      defaultInstance = new SellerMyRequest(true);
      com.randioo.market_server.protocol.Seller.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.market_server.protocol.SellerMyRequest)
  }
  
  public static final class SellerMyResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use SellerMyResponse.newBuilder() to construct.
    private SellerMyResponse() {
      initFields();
    }
    private SellerMyResponse(boolean noInit) {}
    
    private static final SellerMyResponse defaultInstance;
    public static SellerMyResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public SellerMyResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.market_server.protocol.Seller.internal_static_com_randioo_market_server_protocol_SellerMyResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.market_server.protocol.Seller.internal_static_com_randioo_market_server_protocol_SellerMyResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.market_server.protocol.Seller.SellerMyResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SellerMyResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.market_server.protocol.Seller.SellerMyResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.market_server.protocol.Seller.SellerMyResponse result;
      
      // Construct using com.randioo.market_server.protocol.Seller.SellerMyResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.market_server.protocol.Seller.SellerMyResponse();
        return builder;
      }
      
      protected com.randioo.market_server.protocol.Seller.SellerMyResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.market_server.protocol.Seller.SellerMyResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.market_server.protocol.Seller.SellerMyResponse.getDescriptor();
      }
      
      public com.randioo.market_server.protocol.Seller.SellerMyResponse getDefaultInstanceForType() {
        return com.randioo.market_server.protocol.Seller.SellerMyResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.market_server.protocol.Seller.SellerMyResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.market_server.protocol.Seller.SellerMyResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.market_server.protocol.Seller.SellerMyResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.market_server.protocol.Seller.SellerMyResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.market_server.protocol.Seller.SellerMyResponse) {
          return mergeFrom((com.randioo.market_server.protocol.Seller.SellerMyResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.market_server.protocol.Seller.SellerMyResponse other) {
        if (other == com.randioo.market_server.protocol.Seller.SellerMyResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.market_server.protocol.SellerMyResponse)
    }
    
    static {
      defaultInstance = new SellerMyResponse(true);
      com.randioo.market_server.protocol.Seller.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.market_server.protocol.SellerMyResponse)
  }
  
  public static final class SCSellerMyMessage extends
      com.google.protobuf.GeneratedMessage {
    // Use SCSellerMyMessage.newBuilder() to construct.
    private SCSellerMyMessage() {
      initFields();
    }
    private SCSellerMyMessage(boolean noInit) {}
    
    private static final SCSellerMyMessage defaultInstance;
    public static SCSellerMyMessage getDefaultInstance() {
      return defaultInstance;
    }
    
    public SCSellerMyMessage getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.market_server.protocol.Seller.internal_static_com_randioo_market_server_protocol_SCSellerMyMessage_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.market_server.protocol.Seller.internal_static_com_randioo_market_server_protocol_SCSellerMyMessage_fieldAccessorTable;
    }
    
    // repeated .com.randioo.market_server.protocol.GoodsTypeData GoodsTypeData = 1;
    public static final int GOODSTYPEDATA_FIELD_NUMBER = 1;
    private java.util.List<com.randioo.market_server.protocol.Entity.GoodsTypeData> goodsTypeData_ =
      java.util.Collections.emptyList();
    public java.util.List<com.randioo.market_server.protocol.Entity.GoodsTypeData> getGoodsTypeDataList() {
      return goodsTypeData_;
    }
    public int getGoodsTypeDataCount() { return goodsTypeData_.size(); }
    public com.randioo.market_server.protocol.Entity.GoodsTypeData getGoodsTypeData(int index) {
      return goodsTypeData_.get(index);
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      for (com.randioo.market_server.protocol.Entity.GoodsTypeData element : getGoodsTypeDataList()) {
        output.writeMessage(1, element);
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      for (com.randioo.market_server.protocol.Entity.GoodsTypeData element : getGoodsTypeDataList()) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(1, element);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.market_server.protocol.Seller.SCSellerMyMessage parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SCSellerMyMessage parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SCSellerMyMessage parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SCSellerMyMessage parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SCSellerMyMessage parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SCSellerMyMessage parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SCSellerMyMessage parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Seller.SCSellerMyMessage parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.Seller.SCSellerMyMessage parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.Seller.SCSellerMyMessage parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.market_server.protocol.Seller.SCSellerMyMessage prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.market_server.protocol.Seller.SCSellerMyMessage result;
      
      // Construct using com.randioo.market_server.protocol.Seller.SCSellerMyMessage.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.market_server.protocol.Seller.SCSellerMyMessage();
        return builder;
      }
      
      protected com.randioo.market_server.protocol.Seller.SCSellerMyMessage internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.market_server.protocol.Seller.SCSellerMyMessage();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.market_server.protocol.Seller.SCSellerMyMessage.getDescriptor();
      }
      
      public com.randioo.market_server.protocol.Seller.SCSellerMyMessage getDefaultInstanceForType() {
        return com.randioo.market_server.protocol.Seller.SCSellerMyMessage.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.market_server.protocol.Seller.SCSellerMyMessage build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.market_server.protocol.Seller.SCSellerMyMessage buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.market_server.protocol.Seller.SCSellerMyMessage buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        if (result.goodsTypeData_ != java.util.Collections.EMPTY_LIST) {
          result.goodsTypeData_ =
            java.util.Collections.unmodifiableList(result.goodsTypeData_);
        }
        com.randioo.market_server.protocol.Seller.SCSellerMyMessage returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.market_server.protocol.Seller.SCSellerMyMessage) {
          return mergeFrom((com.randioo.market_server.protocol.Seller.SCSellerMyMessage)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.market_server.protocol.Seller.SCSellerMyMessage other) {
        if (other == com.randioo.market_server.protocol.Seller.SCSellerMyMessage.getDefaultInstance()) return this;
        if (!other.goodsTypeData_.isEmpty()) {
          if (result.goodsTypeData_.isEmpty()) {
            result.goodsTypeData_ = new java.util.ArrayList<com.randioo.market_server.protocol.Entity.GoodsTypeData>();
          }
          result.goodsTypeData_.addAll(other.goodsTypeData_);
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 10: {
              com.randioo.market_server.protocol.Entity.GoodsTypeData.Builder subBuilder = com.randioo.market_server.protocol.Entity.GoodsTypeData.newBuilder();
              input.readMessage(subBuilder, extensionRegistry);
              addGoodsTypeData(subBuilder.buildPartial());
              break;
            }
          }
        }
      }
      
      
      // repeated .com.randioo.market_server.protocol.GoodsTypeData GoodsTypeData = 1;
      public java.util.List<com.randioo.market_server.protocol.Entity.GoodsTypeData> getGoodsTypeDataList() {
        return java.util.Collections.unmodifiableList(result.goodsTypeData_);
      }
      public int getGoodsTypeDataCount() {
        return result.getGoodsTypeDataCount();
      }
      public com.randioo.market_server.protocol.Entity.GoodsTypeData getGoodsTypeData(int index) {
        return result.getGoodsTypeData(index);
      }
      public Builder setGoodsTypeData(int index, com.randioo.market_server.protocol.Entity.GoodsTypeData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        result.goodsTypeData_.set(index, value);
        return this;
      }
      public Builder setGoodsTypeData(int index, com.randioo.market_server.protocol.Entity.GoodsTypeData.Builder builderForValue) {
        result.goodsTypeData_.set(index, builderForValue.build());
        return this;
      }
      public Builder addGoodsTypeData(com.randioo.market_server.protocol.Entity.GoodsTypeData value) {
        if (value == null) {
          throw new NullPointerException();
        }
        if (result.goodsTypeData_.isEmpty()) {
          result.goodsTypeData_ = new java.util.ArrayList<com.randioo.market_server.protocol.Entity.GoodsTypeData>();
        }
        result.goodsTypeData_.add(value);
        return this;
      }
      public Builder addGoodsTypeData(com.randioo.market_server.protocol.Entity.GoodsTypeData.Builder builderForValue) {
        if (result.goodsTypeData_.isEmpty()) {
          result.goodsTypeData_ = new java.util.ArrayList<com.randioo.market_server.protocol.Entity.GoodsTypeData>();
        }
        result.goodsTypeData_.add(builderForValue.build());
        return this;
      }
      public Builder addAllGoodsTypeData(
          java.lang.Iterable<? extends com.randioo.market_server.protocol.Entity.GoodsTypeData> values) {
        if (result.goodsTypeData_.isEmpty()) {
          result.goodsTypeData_ = new java.util.ArrayList<com.randioo.market_server.protocol.Entity.GoodsTypeData>();
        }
        super.addAll(values, result.goodsTypeData_);
        return this;
      }
      public Builder clearGoodsTypeData() {
        result.goodsTypeData_ = java.util.Collections.emptyList();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.market_server.protocol.SCSellerMyMessage)
    }
    
    static {
      defaultInstance = new SCSellerMyMessage(true);
      com.randioo.market_server.protocol.Seller.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.market_server.protocol.SCSellerMyMessage)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_market_server_protocol_SellerRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_market_server_protocol_SellerRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_market_server_protocol_SellerResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_market_server_protocol_SellerResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_market_server_protocol_RevokeSellerRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_market_server_protocol_RevokeSellerRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_market_server_protocol_RevokeSellerResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_market_server_protocol_RevokeSellerResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_market_server_protocol_SellerMyRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_market_server_protocol_SellerMyRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_market_server_protocol_SellerMyResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_market_server_protocol_SellerMyResponse_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_market_server_protocol_SCSellerMyMessage_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_market_server_protocol_SCSellerMyMessage_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\014Seller.proto\022\"com.randioo.market_serve" +
      "r.protocol\032\014Entity.proto\"[\n\rSellerReques" +
      "t\022J\n\016SellerInfoData\030\001 \001(\01322.com.randioo." +
      "market_server.protocol.SellerInfoData\"j\n" +
      "\016SellerResponse\022\024\n\terrorCode\030\001 \001(\005:\0011\022B\n" +
      "\nsellerData\030\002 \001(\0132..com.randioo.market_s" +
      "erver.protocol.SellerData\"f\n\023RevokeSelle" +
      "rRequest\022\014\n\004type\030\001 \001(\t\022\r\n\005price\030\002 \001(\t\022\023\n" +
      "\013sellAccount\030\003 \001(\t\022\016\n\006sellId\030\004 \001(\005\022\r\n\005co" +
      "unt\030\005 \001(\005\">\n\024RevokeSellerResponse\022\024\n\terr",
      "orCode\030\001 \001(\005:\0011\022\020\n\010freeback\030\002 \001(\t\"\"\n\017Sel" +
      "lerMyRequest\022\017\n\007account\030\001 \001(\t\"(\n\020SellerM" +
      "yResponse\022\024\n\terrorCode\030\001 \001(\005:\0011\"]\n\021SCSel" +
      "lerMyMessage\022H\n\rGoodsTypeData\030\001 \003(\01321.co" +
      "m.randioo.market_server.protocol.GoodsTy" +
      "peData"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_market_server_protocol_SellerRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_market_server_protocol_SellerRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_market_server_protocol_SellerRequest_descriptor,
              new java.lang.String[] { "SellerInfoData", },
              com.randioo.market_server.protocol.Seller.SellerRequest.class,
              com.randioo.market_server.protocol.Seller.SellerRequest.Builder.class);
          internal_static_com_randioo_market_server_protocol_SellerResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_market_server_protocol_SellerResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_market_server_protocol_SellerResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "SellerData", },
              com.randioo.market_server.protocol.Seller.SellerResponse.class,
              com.randioo.market_server.protocol.Seller.SellerResponse.Builder.class);
          internal_static_com_randioo_market_server_protocol_RevokeSellerRequest_descriptor =
            getDescriptor().getMessageTypes().get(2);
          internal_static_com_randioo_market_server_protocol_RevokeSellerRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_market_server_protocol_RevokeSellerRequest_descriptor,
              new java.lang.String[] { "Type", "Price", "SellAccount", "SellId", "Count", },
              com.randioo.market_server.protocol.Seller.RevokeSellerRequest.class,
              com.randioo.market_server.protocol.Seller.RevokeSellerRequest.Builder.class);
          internal_static_com_randioo_market_server_protocol_RevokeSellerResponse_descriptor =
            getDescriptor().getMessageTypes().get(3);
          internal_static_com_randioo_market_server_protocol_RevokeSellerResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_market_server_protocol_RevokeSellerResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "Freeback", },
              com.randioo.market_server.protocol.Seller.RevokeSellerResponse.class,
              com.randioo.market_server.protocol.Seller.RevokeSellerResponse.Builder.class);
          internal_static_com_randioo_market_server_protocol_SellerMyRequest_descriptor =
            getDescriptor().getMessageTypes().get(4);
          internal_static_com_randioo_market_server_protocol_SellerMyRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_market_server_protocol_SellerMyRequest_descriptor,
              new java.lang.String[] { "Account", },
              com.randioo.market_server.protocol.Seller.SellerMyRequest.class,
              com.randioo.market_server.protocol.Seller.SellerMyRequest.Builder.class);
          internal_static_com_randioo_market_server_protocol_SellerMyResponse_descriptor =
            getDescriptor().getMessageTypes().get(5);
          internal_static_com_randioo_market_server_protocol_SellerMyResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_market_server_protocol_SellerMyResponse_descriptor,
              new java.lang.String[] { "ErrorCode", },
              com.randioo.market_server.protocol.Seller.SellerMyResponse.class,
              com.randioo.market_server.protocol.Seller.SellerMyResponse.Builder.class);
          internal_static_com_randioo_market_server_protocol_SCSellerMyMessage_descriptor =
            getDescriptor().getMessageTypes().get(6);
          internal_static_com_randioo_market_server_protocol_SCSellerMyMessage_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_market_server_protocol_SCSellerMyMessage_descriptor,
              new java.lang.String[] { "GoodsTypeData", },
              com.randioo.market_server.protocol.Seller.SCSellerMyMessage.class,
              com.randioo.market_server.protocol.Seller.SCSellerMyMessage.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.market_server.protocol.Entity.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
