// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: SystemInfo.proto

package com.randioo.market_server.protocol;

public final class SystemInfo {
  private SystemInfo() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
  }
  public static final class SystemInfoRequest extends
      com.google.protobuf.GeneratedMessage {
    // Use SystemInfoRequest.newBuilder() to construct.
    private SystemInfoRequest() {
      initFields();
    }
    private SystemInfoRequest(boolean noInit) {}
    
    private static final SystemInfoRequest defaultInstance;
    public static SystemInfoRequest getDefaultInstance() {
      return defaultInstance;
    }
    
    public SystemInfoRequest getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.market_server.protocol.SystemInfo.internal_static_com_randioo_market_server_protocol_SystemInfoRequest_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.market_server.protocol.SystemInfo.internal_static_com_randioo_market_server_protocol_SystemInfoRequest_fieldAccessorTable;
    }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest result;
      
      // Construct using com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest();
        return builder;
      }
      
      protected com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest.getDescriptor();
      }
      
      public com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest getDefaultInstanceForType() {
        return com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest) {
          return mergeFrom((com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest other) {
        if (other == com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest.getDefaultInstance()) return this;
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
          }
        }
      }
      
      
      // @@protoc_insertion_point(builder_scope:com.randioo.market_server.protocol.SystemInfoRequest)
    }
    
    static {
      defaultInstance = new SystemInfoRequest(true);
      com.randioo.market_server.protocol.SystemInfo.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.market_server.protocol.SystemInfoRequest)
  }
  
  public static final class SystemInfoResponse extends
      com.google.protobuf.GeneratedMessage {
    // Use SystemInfoResponse.newBuilder() to construct.
    private SystemInfoResponse() {
      initFields();
    }
    private SystemInfoResponse(boolean noInit) {}
    
    private static final SystemInfoResponse defaultInstance;
    public static SystemInfoResponse getDefaultInstance() {
      return defaultInstance;
    }
    
    public SystemInfoResponse getDefaultInstanceForType() {
      return defaultInstance;
    }
    
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return com.randioo.market_server.protocol.SystemInfo.internal_static_com_randioo_market_server_protocol_SystemInfoResponse_descriptor;
    }
    
    protected com.google.protobuf.GeneratedMessage.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return com.randioo.market_server.protocol.SystemInfo.internal_static_com_randioo_market_server_protocol_SystemInfoResponse_fieldAccessorTable;
    }
    
    // optional int32 errorCode = 1 [default = 1];
    public static final int ERRORCODE_FIELD_NUMBER = 1;
    private boolean hasErrorCode;
    private int errorCode_ = 1;
    public boolean hasErrorCode() { return hasErrorCode; }
    public int getErrorCode() { return errorCode_; }
    
    // optional string serTime = 2;
    public static final int SERTIME_FIELD_NUMBER = 2;
    private boolean hasSerTime;
    private java.lang.String serTime_ = "";
    public boolean hasSerTime() { return hasSerTime; }
    public java.lang.String getSerTime() { return serTime_; }
    
    // optional string state = 3;
    public static final int STATE_FIELD_NUMBER = 3;
    private boolean hasState;
    private java.lang.String state_ = "";
    public boolean hasState() { return hasState; }
    public java.lang.String getState() { return state_; }
    
    // optional string startTime = 4;
    public static final int STARTTIME_FIELD_NUMBER = 4;
    private boolean hasStartTime;
    private java.lang.String startTime_ = "";
    public boolean hasStartTime() { return hasStartTime; }
    public java.lang.String getStartTime() { return startTime_; }
    
    // optional string endTime = 5;
    public static final int ENDTIME_FIELD_NUMBER = 5;
    private boolean hasEndTime;
    private java.lang.String endTime_ = "";
    public boolean hasEndTime() { return hasEndTime; }
    public java.lang.String getEndTime() { return endTime_; }
    
    private void initFields() {
    }
    public final boolean isInitialized() {
      return true;
    }
    
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      getSerializedSize();
      if (hasErrorCode()) {
        output.writeInt32(1, getErrorCode());
      }
      if (hasSerTime()) {
        output.writeString(2, getSerTime());
      }
      if (hasState()) {
        output.writeString(3, getState());
      }
      if (hasStartTime()) {
        output.writeString(4, getStartTime());
      }
      if (hasEndTime()) {
        output.writeString(5, getEndTime());
      }
      getUnknownFields().writeTo(output);
    }
    
    private int memoizedSerializedSize = -1;
    public int getSerializedSize() {
      int size = memoizedSerializedSize;
      if (size != -1) return size;
    
      size = 0;
      if (hasErrorCode()) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(1, getErrorCode());
      }
      if (hasSerTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(2, getSerTime());
      }
      if (hasState()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(3, getState());
      }
      if (hasStartTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(4, getStartTime());
      }
      if (hasEndTime()) {
        size += com.google.protobuf.CodedOutputStream
          .computeStringSize(5, getEndTime());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSerializedSize = size;
      return size;
    }
    
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data).buildParsed();
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return newBuilder().mergeFrom(data, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      Builder builder = newBuilder();
      if (builder.mergeDelimitedFrom(input, extensionRegistry)) {
        return builder.buildParsed();
      } else {
        return null;
      }
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input).buildParsed();
    }
    public static com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return newBuilder().mergeFrom(input, extensionRegistry)
               .buildParsed();
    }
    
    public static Builder newBuilder() { return Builder.create(); }
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder(com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse prototype) {
      return newBuilder().mergeFrom(prototype);
    }
    public Builder toBuilder() { return newBuilder(this); }
    
    public static final class Builder extends
        com.google.protobuf.GeneratedMessage.Builder<Builder> {
      private com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse result;
      
      // Construct using com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse.newBuilder()
      private Builder() {}
      
      private static Builder create() {
        Builder builder = new Builder();
        builder.result = new com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse();
        return builder;
      }
      
      protected com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse internalGetResult() {
        return result;
      }
      
      public Builder clear() {
        if (result == null) {
          throw new IllegalStateException(
            "Cannot call clear() after build().");
        }
        result = new com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse();
        return this;
      }
      
      public Builder clone() {
        return create().mergeFrom(result);
      }
      
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse.getDescriptor();
      }
      
      public com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse getDefaultInstanceForType() {
        return com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse.getDefaultInstance();
      }
      
      public boolean isInitialized() {
        return result.isInitialized();
      }
      public com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse build() {
        if (result != null && !isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return buildPartial();
      }
      
      private com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse buildParsed()
          throws com.google.protobuf.InvalidProtocolBufferException {
        if (!isInitialized()) {
          throw newUninitializedMessageException(
            result).asInvalidProtocolBufferException();
        }
        return buildPartial();
      }
      
      public com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse buildPartial() {
        if (result == null) {
          throw new IllegalStateException(
            "build() has already been called on this Builder.");
        }
        com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse returnMe = result;
        result = null;
        return returnMe;
      }
      
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse) {
          return mergeFrom((com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }
      
      public Builder mergeFrom(com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse other) {
        if (other == com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse.getDefaultInstance()) return this;
        if (other.hasErrorCode()) {
          setErrorCode(other.getErrorCode());
        }
        if (other.hasSerTime()) {
          setSerTime(other.getSerTime());
        }
        if (other.hasState()) {
          setState(other.getState());
        }
        if (other.hasStartTime()) {
          setStartTime(other.getStartTime());
        }
        if (other.hasEndTime()) {
          setEndTime(other.getEndTime());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        return this;
      }
      
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        com.google.protobuf.UnknownFieldSet.Builder unknownFields =
          com.google.protobuf.UnknownFieldSet.newBuilder(
            this.getUnknownFields());
        while (true) {
          int tag = input.readTag();
          switch (tag) {
            case 0:
              this.setUnknownFields(unknownFields.build());
              return this;
            default: {
              if (!parseUnknownField(input, unknownFields,
                                     extensionRegistry, tag)) {
                this.setUnknownFields(unknownFields.build());
                return this;
              }
              break;
            }
            case 8: {
              setErrorCode(input.readInt32());
              break;
            }
            case 18: {
              setSerTime(input.readString());
              break;
            }
            case 26: {
              setState(input.readString());
              break;
            }
            case 34: {
              setStartTime(input.readString());
              break;
            }
            case 42: {
              setEndTime(input.readString());
              break;
            }
          }
        }
      }
      
      
      // optional int32 errorCode = 1 [default = 1];
      public boolean hasErrorCode() {
        return result.hasErrorCode();
      }
      public int getErrorCode() {
        return result.getErrorCode();
      }
      public Builder setErrorCode(int value) {
        result.hasErrorCode = true;
        result.errorCode_ = value;
        return this;
      }
      public Builder clearErrorCode() {
        result.hasErrorCode = false;
        result.errorCode_ = 1;
        return this;
      }
      
      // optional string serTime = 2;
      public boolean hasSerTime() {
        return result.hasSerTime();
      }
      public java.lang.String getSerTime() {
        return result.getSerTime();
      }
      public Builder setSerTime(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasSerTime = true;
        result.serTime_ = value;
        return this;
      }
      public Builder clearSerTime() {
        result.hasSerTime = false;
        result.serTime_ = getDefaultInstance().getSerTime();
        return this;
      }
      
      // optional string state = 3;
      public boolean hasState() {
        return result.hasState();
      }
      public java.lang.String getState() {
        return result.getState();
      }
      public Builder setState(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasState = true;
        result.state_ = value;
        return this;
      }
      public Builder clearState() {
        result.hasState = false;
        result.state_ = getDefaultInstance().getState();
        return this;
      }
      
      // optional string startTime = 4;
      public boolean hasStartTime() {
        return result.hasStartTime();
      }
      public java.lang.String getStartTime() {
        return result.getStartTime();
      }
      public Builder setStartTime(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasStartTime = true;
        result.startTime_ = value;
        return this;
      }
      public Builder clearStartTime() {
        result.hasStartTime = false;
        result.startTime_ = getDefaultInstance().getStartTime();
        return this;
      }
      
      // optional string endTime = 5;
      public boolean hasEndTime() {
        return result.hasEndTime();
      }
      public java.lang.String getEndTime() {
        return result.getEndTime();
      }
      public Builder setEndTime(java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  result.hasEndTime = true;
        result.endTime_ = value;
        return this;
      }
      public Builder clearEndTime() {
        result.hasEndTime = false;
        result.endTime_ = getDefaultInstance().getEndTime();
        return this;
      }
      
      // @@protoc_insertion_point(builder_scope:com.randioo.market_server.protocol.SystemInfoResponse)
    }
    
    static {
      defaultInstance = new SystemInfoResponse(true);
      com.randioo.market_server.protocol.SystemInfo.internalForceInit();
      defaultInstance.initFields();
    }
    
    // @@protoc_insertion_point(class_scope:com.randioo.market_server.protocol.SystemInfoResponse)
  }
  
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_market_server_protocol_SystemInfoRequest_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_market_server_protocol_SystemInfoRequest_fieldAccessorTable;
  private static com.google.protobuf.Descriptors.Descriptor
    internal_static_com_randioo_market_server_protocol_SystemInfoResponse_descriptor;
  private static
    com.google.protobuf.GeneratedMessage.FieldAccessorTable
      internal_static_com_randioo_market_server_protocol_SystemInfoResponse_fieldAccessorTable;
  
  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\020SystemInfo.proto\022\"com.randioo.market_s" +
      "erver.protocol\032\014Entity.proto\"\023\n\021SystemIn" +
      "foRequest\"n\n\022SystemInfoResponse\022\024\n\terror" +
      "Code\030\001 \001(\005:\0011\022\017\n\007serTime\030\002 \001(\t\022\r\n\005state\030" +
      "\003 \001(\t\022\021\n\tstartTime\030\004 \001(\t\022\017\n\007endTime\030\005 \001(" +
      "\t"
    };
    com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner assigner =
      new com.google.protobuf.Descriptors.FileDescriptor.InternalDescriptorAssigner() {
        public com.google.protobuf.ExtensionRegistry assignDescriptors(
            com.google.protobuf.Descriptors.FileDescriptor root) {
          descriptor = root;
          internal_static_com_randioo_market_server_protocol_SystemInfoRequest_descriptor =
            getDescriptor().getMessageTypes().get(0);
          internal_static_com_randioo_market_server_protocol_SystemInfoRequest_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_market_server_protocol_SystemInfoRequest_descriptor,
              new java.lang.String[] { },
              com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest.class,
              com.randioo.market_server.protocol.SystemInfo.SystemInfoRequest.Builder.class);
          internal_static_com_randioo_market_server_protocol_SystemInfoResponse_descriptor =
            getDescriptor().getMessageTypes().get(1);
          internal_static_com_randioo_market_server_protocol_SystemInfoResponse_fieldAccessorTable = new
            com.google.protobuf.GeneratedMessage.FieldAccessorTable(
              internal_static_com_randioo_market_server_protocol_SystemInfoResponse_descriptor,
              new java.lang.String[] { "ErrorCode", "SerTime", "State", "StartTime", "EndTime", },
              com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse.class,
              com.randioo.market_server.protocol.SystemInfo.SystemInfoResponse.Builder.class);
          return null;
        }
      };
    com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.randioo.market_server.protocol.Entity.getDescriptor(),
        }, assigner);
  }
  
  public static void internalForceInit() {}
  
  // @@protoc_insertion_point(outer_class_scope)
}
